- src/Utils.ts
- src/pages/Stake/Active/ManageBond.tsx
- src/pages/Stake/Active/index.tsx
- src/pages/Stake/Setup/index.tsx
- src/pages/Stake/index.tsx
Currently the totalUnlocking calculation calls the toNumber() on the unlocking object instead of unlocking.val which throws errors if the account has any unlocking values.
To reproduce, 
1- connect a stash account with some unbonded value. 
2- go to sraking tab
```
web3Enable: Enabled 2 extensions: talisman/1.4.3, polkadot-js/0.42.2
logger.js:62 2022-05-12 09:48:20        API/INIT: RPC methods not decorated: state_trieMigrationStatus
ly @ logger.js:62
react-dom.production.min.js:186 TypeError: d[g].toNumber is not a function
at Y5 (index.tsx:34:46)
at yn (react-dom.production.min.js:166:137)
at wi (react-dom.production.min.js:289:386)
at bu (react-dom.production.min.js:279:389)
at mu (react-dom.production.min.js:279:320)
at gu (react-dom.production.min.js:279:180)
at lu …
```
> fix for unlocking calculation

- src/library/Graphs/StatBoxPie.tsx
- src/library/StatBoxList/Item.tsx
- src/library/StatBoxList/Number.tsx
- src/library/StatBoxList/Pie.tsx
- src/library/StatBoxList/Text.tsx
- src/library/StatBoxList/index.tsx
- src/pages/Overview/index.tsx
- src/pages/Payouts/index.tsx
- src/pages/Pools/index.tsx
- src/pages/Stake/Active/index.tsx
- src/pages/validators/Browse.tsx
These will address the #39 to refactor breakdown StatBox Items to separate components. If something like this makes sense we can further customize the chart statboxes to have a new statbox for era with a pie or doughnut timer.
main changes are:
- instead of one Item it will breakdown the stat list items to 3 different components (PieStatBox, TextStatBox, NumberStatBox)
- adds a StatBoxListItem to wrap StatBoxes that are a list item
I use prettier for formatting so some changes are due to fromatter! if there is a formatter/linter that we use for the project I can reformat the changes based on that.
> pass stat items as StatBoxListItems to StatBoxList

- src/Providers.tsx
- src/constants.ts
- src/contexts/Api.tsx
- src/contexts/Network/index.tsx
- src/contexts/SessionEra/defaults.ts
- src/contexts/SessionEra/index.tsx
- src/library/StatBoxList/Pie.tsx
- src/pages/Overview/index.tsx
- src/pages/Pools/index.tsx
- src/pages/Stake/Active/index.tsx
- src/pages/validators/Browse.tsx
These changes should address #33 
-sets the pieStat params to separate groups for stat and graph values, to be able to set independent values for the graph and texts.
- adds a SessionEra context to subscribe to the era and epoch progress.
- Also noticed the unsub is missing in the NetworkMetrics context. I also added the unsub to the state to be called when unmounts.
> Add a graph for era progress in the validator page

- src/constants.ts
- src/contexts/Messages.tsx
- src/contexts/Staking/index.tsx
- src/library/Account/Wrapper.ts
- src/library/Account/index.tsx
- src/library/Form/BondInput/index.tsx
- src/library/Form/BondInputWithFeedback/index.tsx
- src/library/Headers/Connected.tsx
- src/library/SideMenu/Item.tsx
- src/library/SideMenu/Wrapper.ts
- src/library/SideMenu/index.tsx
- src/modals/Nominate/index.tsx
- src/modals/StopNominating/index.tsx
- src/modals/UpdateBond/Forms.tsx
- src/modals/UpdateController/index.tsx
- src/modals/UpdatePayee/index.tsx
- src/pages/Stake/Active/ControllerNotImported.tsx
- src/pages/Stake/Active/index.tsx
- src/pages/Stake/Setup/SetController.tsx
This PR revamps the support for when a controller account is set but not imported.
We have a warning symbol in the side menu, along with a new module on the Stake page to notify the user of the issue:
The warning icon in the minimised side menu is a yellow circle:
Extrinsics that require the controller account have been disabled and accompanied with a warning in the event it is missing:
Extrinsics affected:
- update payee
- unbond some
- unbond all
- start nominating (from active stage)
- stop nominating
> Controller Not Imported Support

- src/Wrappers.tsx
- src/contexts/Staking/defaults.ts
- src/contexts/Staking/index.tsx
- src/contexts/UI.tsx
- src/library/Button/index.tsx
- src/library/Headers/index.tsx
- src/library/SideMenu/index.tsx
- src/library/StatusLabel/index.tsx
- src/pages/Favourites/index.tsx
- src/pages/Overview/Announcements/index.tsx
- src/pages/Stake/Active/BondedGraph.tsx
- src/pages/Stake/Active/ControllerNotImported.tsx
- src/pages/Stake/Active/ManageBond.tsx
- src/pages/Stake/Active/Nominations/index.tsx
- src/pages/Stake/Active/Stats/ActiveNominations.tsx
- src/pages/Stake/Active/index.tsx
- src/pages/Stake/Setup/index.tsx
- src/pages/Stake/Wrappers.tsx
- src/pages/Stake/index.tsx
- src/pages/Validators/index.tsx
This PR tackles #32 by removing the Stake page preloader completely and defaulting to the Active page.
The bulk of the changes pertain to:
- Ensuring the correct default values are displayed as the network syncs and realises the active account is not staking.
- Disabling buttons when not staking / network is syncing.
-  A "Start Staking" button that navigates the user to the Setup form. An `onSetup` context variable is introduced to keep the user on the Setup page if they want to navigate through the app while setting up their positions.
The page also gracefully falls back to default values and re-populates on network change. 
Not staking / default display:
Setup page with Back button:
> Remove Stake Preloading: Active Page By Default

- src/library/Account/Wrapper.ts
- src/library/Form/AccountDropdown/Wrappers.ts
- src/library/Form/AccountDropdown/index.tsx
- src/library/Form/AccountSelect/Wrappers.ts
- src/library/Form/BondStatusBar/index.tsx
- src/library/Form/Dropdown/index.tsx
- src/library/Graphs/Wrappers.ts
- src/library/Headers/Connected.tsx
- src/modals/ConnectAccounts/Accounts.tsx
- src/modals/ConnectAccounts/Wrapper.ts
- src/modals/UpdateController/index.tsx
- src/modals/UpdatePayee/index.tsx
- src/pages/Overview/ActiveAccount.tsx
- src/pages/Overview/BalanceGraph.tsx
- src/pages/Overview/Wrappers.ts
- src/pages/Overview/index.tsx
- src/pages/Stake/Active/ControllerNotImported.tsx
- src/pages/Stake/Active/ManageBond.tsx
Polishing up the interface in various ways ensuring there are no edge case UX bugs.
The  dropdown for selecting controller accounts and payee options have been updated, showing the currently active item alongside the new item. The search box has been separated from the currently-selected item:
Account boxes have a max width and handle account name overflow:
Active account on Overview has an overflow fix:
In addition to the account selection boxes:
And long balance values alongside graphs are also allowed to be overflowed:
> Dropdown Enhancements + Overflow Fixes

- src/constants.ts
- src/contexts/Api/defaults.ts
- src/contexts/Api/index.tsx
- src/library/NetworkBar/Status.tsx
- src/library/NetworkBar/index.tsx
- src/types/api.ts
- src/types/index.ts
I've began introducing types to the project to cut down on the `any` usage. 
The convention i've opted for is to default contexts as null. E.g:
```
export const APIContext = React.createContext<APIContextInterface | null>(null);
```
I have used typecasting when consuming contexts as to prevent the compiler flagging `null` warnings. E.g:
```
const { status } = useApi() as APIContextInterface;
```
I wanted to run this past @hamidra before continuing. The other option is to have default functions in the context, but this introduces other issues like unused variables and inconsistencies in function logic between the context definition and injected provider functions. I think this approach is good enough at least for the initial type support we need to introduce.
> Introduce Types

- src/contexts/Pools/index.tsx
- src/contexts/Validators/index.tsx
- src/library/Pool/index.tsx
- src/library/PoolList/index.tsx
This PR adds a subscription to a pool list's metadata. We assume that the bytes returned by `nominationPools.metedata` is a string, and fallback to display the pool's address if an empty string is returned.
The mechanism behind this is the same as validator lists, whereby a batch of pool items (every pool in a PoolList) is fetched as one subscription, under a particular "batch key".  This asynchronous batching maintains high responsiveness and overall performance of the app, and could be expanded with additional pool metrics in the future (one batch can handle multiple subscriptions).
> Nomination Pools metadata subscription

- src/library/Graphs/Wrappers.ts
- src/pages.ts
- src/pages/Overview/BalanceGraph.tsx
- src/theme/default.ts
Note that the pool balance is hard-coded zero until we have memberships fully hooked up.
- Pooling stat added to Balances graph
- New purple color introduced (up for debate)
- Assistant item explaining that pool balance is not held in your account, unlike staked balance.
> Add Pooling to Balances Graph

- src/contexts/Account.tsx
- src/contexts/Pools/index.tsx
- src/contexts/Validators/index.tsx
- src/library/PoolAccount/index.tsx
- src/pages/Pools/Roles.tsx
This should fix bug: #79 in the nomination pool page, where the users who are not in an active pool see the wrong pool context.
> reset activeBondedPool when unsubscribe

- src/contexts/Subscan.tsx
- src/library/Graphs/PayoutBar.tsx
- src/library/Graphs/PayoutLine.tsx
- src/library/Graphs/Utils.ts
- src/pages/Overview/Payouts.tsx
- src/pages/Overview/index.tsx
- src/pages/Payouts/index.tsx
This PR introduces an algorithm that takes payouts and formats them in daily order for the payout graphs. When the pools API is ready we can look into further formatting options like stacking a bar with payouts (both staking and pool rewards) to represent individual payments on that day.
For now, the following improvements were made:
- Where multiple payouts are received on the same day, they are added together and represented as daily income.
- Days where no payouts were made are represented as a zero-payout day.
- Where there has been inactivity for a number of days since the last payout, zero-payout days are added from the last payout day to the current day.
(Notice duplicate day records / missing days issues)
> Chronological payout graphs

- src/Providers.tsx
- src/Router.tsx
- src/Wrappers.tsx
- src/contexts/Palette.tsx
- src/contexts/Themes.tsx
- src/library/Graphs/Bonded.tsx
- src/library/Graphs/Wrappers.ts
- src/library/Menu/Wrappers.ts
- src/library/Palette/Wrappers.ts
- src/library/Palette/index.tsx
- src/library/SideMenu/Wrapper.ts
- src/library/SideMenu/index.tsx
- src/modals/ValidatorMetrics/index.tsx
- src/theme/default.ts
- src/theme/index.ts
This PR adds a palette for theming the dashboard, and introduces multi-dimensional theming in the form of card styles.
Cards have been flat, but users now have the option of either having a bordered or shadowed cards:
> Theming Palette Intro

- src/contexts/Balances/index.tsx
- src/library/Form/AccountDropdown/Wrappers.ts
- src/library/Form/AccountDropdown/index.tsx
- src/library/Form/Utils/getEligibleControllers.tsx
- src/library/Form/types.ts
- src/modals/UpdateController/index.tsx
- src/pages/Stake/Setup/SetController.tsx
Introduces a `getEligibleControllers` hook, and ensures the `UpdateController` modal only allows accounts that are eligible (have ED, not already controller).
Accounts are ordered by whether they have ED and available as controllers, and disabled otherwise. `UpdateController`:
> Rb enhance select controller

- src/library/Help/Items/External.tsx
- src/library/Help/Wrappers.ts
- Remove duplicate `%%` that was appearing for width;
- Remove unused `label` param;
- Fix scrollbar issue in articles (see below)
> Minor fixes

- src/contexts/Connect/index.tsx
Fixes an issue where an account that existed in multiple extensions would be imported multiple times. The account is now imported from the first extension it is found in.
> Filter accounts already imported

- src/Providers.tsx
- src/contexts/Connect/Hooks/useImportAccounts.tsx
- src/contexts/Connect/Hooks/useImportExtension.tsx
- src/contexts/Connect/Utils.ts
- src/contexts/Connect/defaults.ts
- src/contexts/Connect/index.tsx
- src/contexts/Connect/types.ts
- src/contexts/Extensions/defaults.ts
- src/contexts/Extensions/index.tsx
- src/contexts/Extensions/types.ts
- src/library/Hooks/useSubmitExtrinsic/index.tsx
- src/modals/ConnectAccounts/Account.tsx
- src/modals/ConnectAccounts/Extension.tsx
- src/modals/ConnectAccounts/index.tsx
This PR simplifies the `Connect` context and makes it a lot more readable.
- Adds a new `Extensions` context and moves extension storage to it from `Connect`.
- Moves some logic from `Connect` into `Utils`.
- Introduces a new `useImportExtension` hook to abstract injected account connection logic and remove repeated code.
> Refactor Connect context

- src/config/extensions/index.ts
- src/contexts/Connect/Hooks/useImportExtension.tsx
- src/contexts/Connect/Utils.ts
- src/contexts/Connect/index.tsx
- src/contexts/Connect/types.ts
- src/contexts/Extensions/index.tsx
- src/contexts/Extensions/types.ts
- src/library/Form/types.ts
- src/library/Hooks/useSubmitExtrinsic/index.tsx
- src/modals/ConnectAccounts/Account.tsx
- src/modals/ConnectAccounts/Extension.tsx
- src/modals/ConnectAccounts/Extensions.tsx
- src/modals/ConnectAccounts/types.ts
This PR formalises the required properties an extension must provide the dashboard in its `injectedWeb3` object.
> Formalise required extension properties in types

- src/library/Hooks/useTimeLeft/index.tsx
- src/library/Hooks/useTimeLeft/types.ts
- src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
This PR fixes network switching bugs that did not clear intervals correctly.
It also introduces a way to update the estimated end time in `useTimeLeft` via a refresh callback function, as well as how often the end time should be updated.
> Timeleft fixes + refresh intervals

- src/library/Hooks/useTimeLeft/index.tsx
Small fix pertaining to refresh counter, deducting 60 seconds on minInterval and 1 second on secInterval. Previously it was deducting 1 second on both intervals.
> Timeleft refresh counter fix

- src/library/Hooks/useEraTimeLeft/index.tsx
- src/library/Hooks/useTimeLeft/index.tsx
- src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
Fixes an issue where `refreshCallback` as not getting the live era time left from the hook. Fix: refactor to a callable function.
> Era Timeleft as Function

- src/contexts/Pools/types.ts
- src/contexts/Setup/defaults.ts
- src/contexts/Setup/index.tsx
- src/contexts/Setup/types.ts
- src/library/Hooks/usePoolFilters/index.tsx
- src/library/Pool/index.tsx
- src/library/PoolList/index.tsx
- src/library/SideMenu/Main.tsx
- src/library/SideMenu/Primary/index.tsx
- src/modals/ManagePool/Forms.tsx
- src/modals/ManagePool/Tasks.tsx
- src/modals/StartStaking/index.tsx
- src/modals/index.tsx
- src/pages/Nominate/Active/Nominations/index.tsx
- src/pages/Nominate/Active/Status.tsx
- src/pages/Nominate/Setup/index.tsx
- src/pages/Overview/StakeStatus/Item.tsx
- src/pages/Overview/StakeStatus/Wrappers.tsx
- src/pages/Overview/StakeStatus/index.tsx
- src/pages/Pools/Create/index.tsx
- src/pages/Pools/Home/ClosurePrompts.tsx
- src/pages/Pools/Home/ManageBond.tsx
- src/pages/Pools/Home/ManagePool/index.tsx
- src/pages/Pools/Home/Members.tsx
- src/pages/Pools/Home/MembersList/Member.tsx
- src/pages/Pools/Home/PoolStats/Header.tsx
- src/pages/Pools/Home/Status/index.tsx
- src/pages/Pools/Home/Status/useStatusButtons.tsx
- src/pages/Pools/Home/context.tsx
- src/pages/Pools/Home/index.tsx
This PR adds new functionality to the dashboard and expands CTA support.
> CTA Part 2: start staking modal + quick links

- src/locale/cn/help.json
- src/locale/en/help.json
The epoch definition is not correct and conflicts with the era definition, which is confusing. 
Source: https://wiki.polkadot.network/docs/learn-staking#eras-and-sessions
> Correct the epoch help definition

- package.json
- yarn.lock
It solves the issue with the list of validators (and others) not being loaded with the light-client.
> fix: upgrade @substrate/connect

- src/contexts/Api/index.tsx
I am not sure why the app was forced to avoid using Substrate Connect Extension, but it seems to me (and have tested it) that the experience (now that extension contains Smoldot v1.0) is identical to RPC  (no hanging connections or non-returned results anymore). 
Would prefer to merge after #774 
Screenshot below shows PSD connected to light client and how all info (especially stats at the bottom of the screen exist):
> Revert Connectivity to Substrate Connect Extension

- package.json
- yarn.lock
Contains the [fix](https://github.com/paritytech/substrate-connect/pull/1400) that was breaking the build of Vite ("veet");
> Bump substrate connect to 0.7.22

- src/contexts/Subscan/defaults.ts
- src/contexts/Subscan/index.tsx
- src/contexts/Subscan/types.ts
- src/library/Graphs/Utils.ts
- src/library/PoolList/index.tsx
- src/library/ValidatorList/index.tsx
- src/pages/Payouts/PayoutList/index.tsx
- src/pages/Payouts/index.tsx
- src/pages/Pools/Home/MembersList/index.tsx
Fixes pertaining to the 1.0.6 release of the dashboard.
> Pre release UX Fixes

- src/modals/UpdatePayee/index.tsx
Fixes an issue that caused an error in `UpdatePayee` when an invalid address was input into `PayeeInput` and the user toggled between options and landed back on the account option.
> Fix Invalid Payee Account

- src/contexts/Hardware/Ledger.tsx
- src/contexts/Hardware/defaults.ts
- src/contexts/Hardware/types.ts
- src/contexts/TxMeta/defaults.ts
- src/contexts/TxMeta/index.tsx
- src/contexts/TxMeta/types.ts
- src/library/Hooks/useLedgerLoop/index.tsx
- src/library/Hooks/useSubmitExtrinsic/index.tsx
- src/locale/cn/modals.json
- src/locale/en/modals.json
More pre-release fixes dealing with Ledger edge cases and simplification of syntax.
> Ledger pre-release fixes 2

- src/library/Headers/index.tsx
The syncing animation is now displayed on the pools page when `bondedPools` and `poolMembers` are yet to be fetched.
> Pools page syncing enhance

- src/library/Graphs/PayoutBar.tsx
- src/library/Graphs/PayoutLine.tsx
- src/library/Graphs/Utils.ts
- src/pages/Overview/index.tsx
- tests/graphs.test.ts
This PR adds logic to pre-process payouts some time prior to the graph starting - if they exist - so the first payout accurately displays its 10-day average. Prior to this solution, the 10 day average always started at zero.
> Pre-process X day average prior to graph start item

- package.json
- yarn.lock
It addresses the issue that caused smoldot to take over the main-thread for seconds. There is still room for improvement, but things just got much much better with this release.
> chore: upgrade `@substrate/connect`

- src/modals/NominateFromFavorites/index.tsx
- src/modals/SelectFavorites/index.tsx
Fixes an issue where you could select `maxNominations - 1` validators instead of `maxNominations` validators.
Fixes #922
> Fix max nominations from favorites

- src/contexts/Balances/defaults.ts
- src/contexts/Balances/index.tsx
- src/contexts/Balances/types.ts
- src/contexts/TransferOptions/defaults.ts
- src/contexts/TransferOptions/index.tsx
- src/contexts/TransferOptions/types.ts
- src/pages/Overview/BalanceChart.tsx
> Introduce `forceReserved`

- package.json
- src/library/BarChart/Wrappers.ts
- src/library/List/index.ts
- src/library/ListItem/Wrappers.ts
- src/library/Overlay/Wrappers.tsx
- src/library/PayeeInput/Wrapper.ts
- src/library/Stat/Wrapper.ts
- src/library/StatBoxList/Wrapper.ts
- src/modals/Connect/Wrappers.ts
- src/pages/Payouts/Wrappers.ts
- yarn.lock
This PR uses the latest version of `@polkadotcloud/core-ui`, that replaces the variable `Inter` font with woff2 alternatives.
https://github.com/paritytech/polkadot-dashboard-ui/pull/215
> use InterSemiBold, deprecate font-variation-settings

- src/library/Hooks/useBatchCall/index.tsx
- src/library/Hooks/useBuildPayload/index.tsx
- src/library/Hooks/useProxySupported/index.tsx
- src/library/Hooks/useSubmitExtrinsic/index.tsx
- src/library/Import/Wrappers.ts
- src/library/SubmitTx/ManualSign/index.tsx
- src/modals/BalanceTest/index.tsx
- src/modals/ImportVault/Reader.tsx
- src/modals/JoinPool/index.tsx
- src/modals/ManagePool/Forms/Commission.tsx
- src/modals/Unstake/index.tsx
- src/modals/UpdateReserve/index.tsx
- src/pages/Nominate/Setup/Summary/index.tsx
- src/pages/Pools/Create/Summary/index.tsx
> 1.0.8 Pre-Release Fixes & Optimisations

- src/config/networks.ts
- src/contexts/TransferOptions/index.tsx
- src/types/index.ts
Adds default fee reserves to each network. 0.1 for DOT and WND, 0.05 for KSM, ensuring that accounts will have some funds to pay for tx fees by default.
> Add defaultFeeReserve

- src/modals/UpdateController/index.tsx
- src/pages/Nominate/Setup/Summary/index.tsx
Fixes the removal of controller arguments for Kusama 0.9.43.
> Fix `bond`, `setController` for Kusama 0.9.43

- Dockerfile
- README.md
- scripts/build-container.sh
This PR adds a Dockerfile.
I did build the image and pushed it to my account to allow testing.
The end product can be tested with:
```
podman run --name staking-dashboard --rm -it -p 8080:80 docker.io/chevdor/polkadot-staking-dashboard
open http://localhost:8080/
```
> Add Dockerfile, script and doc

- src/contexts/Api/defaults.ts
- src/contexts/Api/index.tsx
- src/contexts/Api/types.ts
Continues what #1185 started.
Stores `chain`, `version` and `ss58Prefix` in chain state.
> Fetch initial chain meta, store in API

- src/contexts/Api/index.tsx
- src/contexts/Balances/index.tsx
- src/contexts/Bonded/index.tsx
- src/contexts/Connect/index.tsx
- src/contexts/FastUnstake/index.tsx
- src/contexts/Help/index.tsx
- src/contexts/Migrate/index.tsx
- src/contexts/Modal/index.tsx
- src/contexts/Network/index.tsx
- src/contexts/Pools/ActivePools/index.tsx
- src/contexts/Pools/BondedPools/index.tsx
- src/contexts/Pools/PoolMembers/index.tsx
- src/contexts/Pools/PoolMemberships/index.tsx
- src/contexts/Pools/PoolsConfig/index.tsx
- src/contexts/Proxies/index.tsx
- src/contexts/Setup/index.tsx
- src/contexts/Staking/index.tsx
- src/contexts/Subscan/index.tsx
- src/contexts/TransferOptions/index.tsx
- src/contexts/TxMeta/index.tsx
- src/contexts/UI/index.tsx
- src/contexts/Validators/index.tsx
- src/library/Hooks/useEffectIgnoreInitial/index.tsx
Addresses #1204.
Introduces a hook that ignores `useEffect` logic on the first render.
Cuts down on logic being executed when it is guaranteed to fail (due to API state not yet being synced).
> Add `useEffectIgnoreInitial` hook 

- package.json
- src/library/Help/Wrappers.ts
- src/library/Help/index.tsx
- src/modals/index.tsx
- yarn.lock
Refactors some modal wrappers, renaming the non-card modals to canvases.
This is being merged concurrently with https://github.com/paritytech/polkadot-cloud/pull/316.
> Re-org some Modal wrappers

- package.json
- src/library/Overlay/index.tsx
- src/modals/index.tsx
- yarn.lock
The modal and help canvas now use the same overlay background, so now there is no separate background to overlay an open modal when help is open, causing display issues.
This PR fixes this by transitioning an open model's opacity to 0.1 when help is invoked in a modal.
> Dim modal on help open

- .eslintrc.json
- src/contexts/Api/index.tsx
- src/contexts/Balances/index.tsx
- src/contexts/Bonded/index.tsx
- src/contexts/Extensions/index.tsx
- src/contexts/Extensions/types.ts
- src/contexts/Hardware/Ledger.tsx
- src/contexts/Pools/PoolMemberships/index.tsx
- src/contexts/Proxies/index.tsx
- src/library/Hooks/useBlockNumber/index.tsx
- src/library/ValidatorList/index.tsx
- src/modals/Networks/index.tsx
- src/pages/Pools/Home/index.tsx
This PR re-activates the `@typescript-eslint/ban-ts-comment`, `consistent-return`, and `no-shadow` eslint rules, and the codebase fixed to reflect them. 
Comments have been added on 3 `off` rules to justify their deactivation, and future PRs will review other `off` rules & either remove them, or keep / justify them.
> [Eslint] Activate some eslint rules, fix codebase

- src/library/Form/Bond/BondFeedback.tsx
- src/library/Form/Unbond/UnbondFeedback.tsx
- src/library/Form/types.ts
- src/locale/cn/modals.json
- src/locale/en/modals.json
- src/modals/Bond/index.tsx
- src/modals/JoinPool/index.tsx
- src/modals/Unbond/index.tsx
- src/pages/Nominate/Setup/Bond/index.tsx
- src/pages/Pools/Create/Bond/index.tsx
Fixes an issue where the bond / unbond modals would not resize if bond was not valid & error length changed.
> [Fix] Bond / Unbond modal resize on feedback error length change

- src/contexts/Api/index.tsx
The flag `forceEmbeddedNode` was passed to the provider's connect options;
This flag, makes the client to always use a node embedded within the page and never use the substrate-connect extension. It defaults to `false` thus removing the option will allow the app to connect to the extension
> Allow app to use extension on Light Client

- src/pages/Overview/BalanceLinks.tsx
This PR will add a link to polkawatch in overview, next to subscan. 
The link will be active when there is a nominating account in one of the supported chains.
Polkawatch will directly display the decentralization of the selected account.
> adds polkawatch direct link to decentralization analysis of nomination

- src/contexts/Pools/PoolMemberships/index.tsx
- src/contexts/Pools/types.ts
- src/contexts/TransferOptions/index.tsx
- src/pages/Pools/Home/ManageBond.tsx
This PR fetches the real balance of a pool, and displays in in the `ManageBond` card on the pools page.
There are other areas where pool points are being treated as balances, this should be explored in another PR to ensure balances are being fetched efficiently in large lists.
> Convert points to balance for `PoolMemberships`

- src/Providers.tsx
- src/contexts/Validators/FavoriteValidators/defaults.ts
- src/contexts/Validators/FavoriteValidators/index.tsx
- src/contexts/Validators/ValidatorEntries/defaults.ts
- src/contexts/Validators/ValidatorEntries/index.tsx
- src/contexts/Validators/types.ts
- src/library/GenerateNominations/index.tsx
- src/library/GenerateNominations/useFetchMethods.tsx
- src/library/Headers/index.tsx
- src/library/Hooks/useNominationStatus/index.tsx
- src/library/Hooks/useValidatorFilters/index.tsx
- src/library/ListItem/Labels/FavoriteValidator.tsx
- src/library/ListItem/Labels/Identity.tsx
- src/library/ListItem/Labels/ParaValidator.tsx
- src/library/Pool/index.tsx
- src/library/ValidatorList/Validator/Default.tsx
- src/library/ValidatorList/Validator/Nomination.tsx
- src/modals/NominateFromFavorites/index.tsx
- src/modals/SelectFavorites/index.tsx
- src/pages/Community/Entity.tsx
- src/pages/Community/List.tsx
- src/pages/Nominate/Active/Nominations/index.tsx
- src/pages/Payouts/PayoutList/index.tsx
- src/pages/Validators/AllValidators.tsx
- src/pages/Validators/Favorites.tsx
- src/pages/Validators/Stats/AverageCommission.tsx
Separates favorite validator management from `useValidators`, with misc syntax improvements.
> Favorite validators to own context

- src/library/Card/Wrappers.ts
- src/library/Graphs/types.ts
- src/modals/ValidatorMetrics/index.tsx
- src/pages/Nominate/Active/ControllerNotStash.tsx
- src/pages/Overview/StakeStatus/index.tsx
- src/pages/Overview/index.tsx
- src/pages/Pools/Create/PoolRoles/index.tsx
- src/pages/Pools/Roles/index.tsx
- src/pages/Pools/Roles/types.ts
Legacy classes and refactors for `CardWrapper` so it can be moved to Cloud and use `@container` queries. Includes misc UX fixes.
> Tidy up `CardWrapper` for Cloud and `@container`

- package.json
- src/contexts/Connect/index.tsx
- src/contexts/Hardware/Vault.tsx
- src/contexts/Proxies/index.tsx
- src/library/Account/Default.tsx
- src/library/Account/Pool.tsx
- src/library/ListItem/Labels/Identity.tsx
- src/library/ListItem/Labels/PoolIdentity.tsx
- src/modals/Accounts/Account.tsx
- src/modals/ChangePoolRoles/RoleChange.tsx
- src/modals/ImportLedger/Addresses.tsx
- src/modals/ImportLedger/index.tsx
- src/modals/ValidatorMetrics/index.tsx
- src/pages/Nominate/Setup/Summary/index.tsx
- src/pages/Overview/ActiveAccounts/Item.tsx
- yarn.lock
[PR #492 of polkadot-cloud](https://github.com/paritytech/polkadot-cloud/pull/492) deprecates the clipAddress from @polkadot-cloud/utils for a more advanced function called ellipsisFn;
As a result we need to update the naming here as well;
Visually absolutely nothing is changed, as `ellipsisFn` is defaulting to 6 characters and "center" positioning of the ellipsis
> remove clipAddress and replace it with the more advanced EllipsisFn

- src/contexts/Payouts/index.tsx
- src/locale/cn/modals.json
- src/locale/en/modals.json
- src/modals/ClaimPayouts/Overview.tsx
- Removes "Claim All" due to a transaction block limit that quickly exhausts the function.
- Fixes an issue where syncing was hanging when switching between active nominator accounts with unclaimed payouts.
- Fixes an issue where zero balance unclaimed payouts were being displayed.
Addresses #1429 and #1427.
> Claim payout fixes

- src/App.tsx
- src/Providers.tsx
- src/contexts/Api/index.tsx
- src/contexts/Api/types.ts
- src/contexts/Connect/Hooks/useImportExtension.tsx
- src/contexts/Connect/Utils.ts
- src/contexts/Connect/index.tsx
- src/library/Hooks/index.tsx
This PR expands `Providers`, which are now provided via a hook, which allows state from the `Network` context to be passed into the providers as props.
This refactored component structure is required to abstract `Connect` provider functionality into Polkadot Cloud providers.
Also removes `any` types from `withProviders` hook.
> Providers to hook, provide `network` to providers

- src/Providers.tsx
- src/library/Hooks/index.tsx
Fixes an issue where `withProviders` was resulting in an anonymous component within the hierarchy, which was resulting in unwanted reloads of public assets on network change (Lottie files).
> Refactor `withProviders` to be pure function

- package.json
- src/Providers.tsx
- src/contexts/Connect/ExtensionAccounts/index.tsx
- src/contexts/Connect/ExtensionAccounts/useImportExtension.tsx
- src/contexts/Connect/ImportedAccounts/index.tsx
- src/contexts/Connect/ImportedAccounts/types.ts
- src/contexts/Connect/OtherAccounts/index.tsx
- src/contexts/Connect/OtherAccounts/types.ts
- src/contexts/Connect/Utils.ts
- src/contexts/Hardware/Ledger.tsx
- src/contexts/Hardware/Utils.tsx
- src/contexts/Hardware/Vault.tsx
- src/contexts/Hardware/types.ts
- src/contexts/Staking/index.tsx
- src/contexts/UI/index.tsx
- src/library/Form/types.ts
- src/library/SubmitTx/ManualSign/Ledger.tsx
- src/modals/Connect/ReadOnly.tsx
- src/modals/ImportLedger/Reset.tsx
- src/pages/Pools/Home/index.tsx
- yarn.lock
tidies up imports from `@polkadot-cloud/react`.
> feat(refactor): use simple cloud react imports

- src/library/BarChart/BondedChart.tsx
- src/library/BarChart/Wrappers.ts
- src/modals/ValidatorGeo/index.tsx
Forces a min-width for `ManageBond` graphs when there is small non-zero bar value.
> feat(ux): min non-zero bar segment width

- src/modals/Connect/ReadOnly.tsx
There is an existing bug, for read only accounts.
- Once the account is added, and then "Forget" is pressed, the account will be removed on the background and get disconnected (if connected), but will not dissappear from the Connect modal.
This PR fixes this misbehavior
> Fix Forget read-only account bug

- src/library/Graphs/Utils.ts
Fixes an issue where the earliest payout record was not displayed if the payoutByDay loop broke with an outstanding payout amount.
> fix: missing payout day

- src/canvas/ManageNominations/index.tsx
- src/contexts/NetworkMetrics/index.tsx
- src/contexts/Pools/ActivePools/index.tsx
- src/contexts/Pools/BondedPools/defaults.ts
- src/contexts/Pools/BondedPools/index.tsx
- src/contexts/Pools/PoolMembers/index.tsx
- src/contexts/Pools/types.ts
- src/library/Account/Pool.tsx
- src/library/Hooks/usePoolFilters/index.tsx
- src/library/ListItem/Labels/PoolBonded.tsx
- src/library/ListItem/Labels/PoolIdentity.tsx
- src/library/ListItem/types.ts
- src/library/Pool/index.tsx
- src/library/Pool/types.ts
- src/library/PoolList/Default.tsx
- src/library/PoolList/types.ts
- src/modals/ManagePool/Forms/SetMetadata.tsx
- src/pages/Payouts/PayoutList/index.tsx
- src/pages/Pools/Home/Favorites/index.tsx
- src/pages/Pools/Home/Status/MembershipStatus.tsx
- src/pages/Pools/Home/index.tsx
This PR cuts down on pool subscriptions and deprecates the poolsMetaBatch structure, improving app performance and sync speed.
> feat: pool context optimisations

- package.json
- src/Providers.tsx
- src/contexts/Balances/index.tsx
- src/contexts/Bonded/index.tsx
- src/contexts/Connect/ExternalAccounts/Utils.ts
- src/contexts/Connect/ExternalAccounts/defaults.ts
- src/contexts/Connect/ExternalAccounts/index.tsx
- src/contexts/Connect/ExternalAccounts/types.ts
- src/contexts/Connect/OtherAccounts/defaults.ts
- src/contexts/Connect/OtherAccounts/index.tsx
- src/contexts/Connect/OtherAccounts/types.ts
- src/contexts/Connect/Utils.ts
- src/contexts/Proxies/index.tsx
- src/modals/Connect/ReadOnly.tsx
- yarn.lock
This PR refactors how external accounts are handled, bringing conventions inline with how hardware wallet accounts are handled.
> refactor: revise external account logic, add `ExternalAccountsProvider` context.

- src/consts.ts
- src/contexts/Connect/ExternalAccounts/Utils.ts
- src/contexts/Connect/ExternalAccounts/index.tsx
- src/contexts/Migrate/index.tsx
- src/contexts/Proxies/defaults.ts
- src/contexts/Proxies/index.tsx
- src/contexts/Proxies/types.ts
- src/modals/Accounts/types.ts
- src/modals/Connect/Proxies.tsx
- src/modals/Connect/ReadOnly.tsx
To prevent edge cases in read only account management, system accounts are no longer persisted in local storage.
System accounts are discovered after the initial account import process, and may replace existing `user` based read only accounts. This is a dynamic process, and the `user` added accounts still need to be persisted in local storage. This update will allow these accounts to be remembered even if they are updated to `system` accounts. 
Includes a migration to remove existing `system` external accounts from local storage.
> feat(refactor): don't persist `system` external accounts, remove proxy `delegates` state

- package.json
- src/contexts/Prompt/defaults.tsx
- src/contexts/Prompt/index.tsx
- src/contexts/Prompt/types.ts
- src/library/Import/Wrappers.ts
- src/library/QRCode/Scan.tsx
- src/library/QRCode/types.ts
- src/library/QRCode/util.ts
- src/library/SubmitTx/ManualSign/Vault/SignPrompt.tsx
- src/modals/ImportVault/Reader.tsx
- yarn.lock
Replaces `react-qr-reader` (which takes React 16 as a dependency) with `html5-qrcode`.
> feat(refactor): use `html5-qrcode`, remove `react-qr-reader`

- src/contexts/Connect/OtherAccounts/index.tsx
Removes unneeded ref from the context.
> feat(refactor): remove ref from `OtherAccounts`

- src/contexts/Api/index.tsx
- src/contexts/Api/types.ts
- src/contexts/Pools/PoolMembers/index.tsx
- src/contexts/Pools/PoolsConfig/defaults.ts
- src/contexts/Pools/PoolsConfig/index.tsx
- src/library/NetworkBar/Status.tsx
- src/library/SideMenu/index.tsx
- src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
- src/static/APController/index.ts
- src/static/APController/types.ts
This PR separates the Polkadot JS API `api` and `provider` objects from React completely, cutting down on re-renders and having a better separation of concerns. This PR will pave the way for more API related tasks to be separated from the React component hierarchy.
> feat(refactor): API to static class

- src/contexts/Api/index.tsx
- src/contexts/UI/index.tsx
- src/locale/cn/library.json
- src/locale/en/library.json
- src/pages/Overview/NetworkSats/Announcements.tsx
- src/static/APController/index.ts
Although not a perfect solution as `navigator.onLine` can return false positives (VPN / virtualisation), this PR automatically disconnects the Polkadot JS API when the app goes offline, and reconnects when the app goes online again.
This could be coupled with a polling solution in another PR for further reacting to going offline, and to ping to confirm we are in-fact online when an `online` event is fired.
> feat: use `navigator.onLine` to handle api connection

- package.json
- yarn.lock
Addreses #1754.
- Makes odometer text copyable by highlighting to copy.
- Moves template digits outside of main `odometer` container.
- Uses CSS `user-select: none` to disallow the selection of template digits and transition digits.
> fix: make odometer values copy-able

- src/contexts/Api/index.tsx
- src/library/NetworkBar/Wrappers.ts
- src/library/NetworkBar/index.tsx
- src/static/APController/index.ts
- src/static/APController/types.ts
- src/types/index.ts
This PR sets up a subscription from `APIController`, which reports block numbers to `document` via a custom event. `NetworkBar` then listens for updates and updates its state accordingly.
Block number subscription can be used in a future PR to determine whether the app is offline.
> feat(ux): block number in network bar

- src/static/APController/index.ts
Configures a connection timeout multiplier. First connection attempt times out after 10s. Second 30s, and 60s thereafter.
This caters for a very slow connection edge case.
> feat: timeout multiplier

- src/contexts/Balances/defaults.ts
- src/contexts/Balances/index.tsx
- src/contexts/Balances/types.ts
- src/contexts/UI/index.tsx
Fixes an issue where `balancesSynced` was not being updated to `true` when there were no accounts being imported.
Changes the nae of `balancesSynced` to `balancesInitialSynced`, as this syncing status is only used on the initial page load.
> fix: balances no accounts sync

- package.json
- src/static/APIController/index.ts
- yarn.lock
Rolling back `@substrate/connect` to 0.7, and disabling connection re-attempts if light client is the connection method.
> fix: roll back Substrate Connect

- src/contexts/Balances/defaults.ts
- src/contexts/Balances/index.tsx
- src/contexts/Balances/types.ts
- src/contexts/Staking/defaults.ts
- src/contexts/Staking/index.tsx
- src/contexts/Staking/types.ts
- src/library/Hooks/useActiveBalances/index.tsx
- src/modals/UpdatePayee/index.tsx
- src/pages/Nominate/Active/Status/PayoutDestinationStatus.tsx
- src/pages/Nominate/Setup/Payee/index.tsx
- src/static/BalancesController/defaults.ts
- src/static/BalancesController/index.ts
In preparation to move all of staking metrics to `APIController`, `payee` has been moved to active account subscriptions. Only the payee for the active accounts are now subscribed to, rather than all the imported accounts.
> feat(refactor): Move staking metrics `payee` to active balances

- src/contexts/Api/defaults.ts
- src/contexts/Api/index.tsx
- src/contexts/Api/types.ts
- src/contexts/Staking/defaults.ts
- src/contexts/Staking/index.tsx
- src/contexts/Staking/types.ts
- src/contexts/UI/index.tsx
- src/library/Form/Bond/BondFeedback.tsx
- src/library/Form/NominateStatusBar/index.tsx
- src/library/Form/Unbond/UnbondFeedback.tsx
- src/library/Hooks/useAverageRewardRate/index.tsx
- src/modals/Unbond/index.tsx
- src/pages/Nominate/Active/Stats/MinimumNominatorBond.tsx
- src/pages/Overview/NetworkSats/Announcements.tsx
- src/pages/Overview/NetworkSats/index.tsx
- src/pages/Overview/StakeStatus/Tips/index.tsx
- src/pages/Overview/Stats/SupplyStaked.tsx
- src/pages/Payouts/Stats/LastEraPayout.tsx
- src/pages/Validators/Stats/ActiveValidators.tsx
- src/pages/Validators/Stats/TotalValidators.tsx
- src/static/APIController/index.ts
- src/types/index.ts
Bootstraps staking metrics before subscription to prevent a re-render. deprecates staking metrics in `Staking` context and subscribes via `APIController`.
> feat(refactor): Staking metrics to bootstrap and API

- src/contexts/Connect/ImportedAccounts/index.tsx
- src/contexts/Pools/ActivePools/index.tsx
- src/contexts/Pools/PoolMemberships/index.tsx
Introduces a safe-guard to prevent unnecessary re-renders on account updates. Since the UI only cares about the address and name of the account, accounts are ordered and stringified with these properties only. The result of this function is used as hook dependencies in `ImportedAccounts`.
Miscellaneous useEffect fixes for pools also have been applied to prevent resetting of memberships state.
> fix: Accounts render safeguard, pool useEffect fixes 

- src/Providers.tsx
- src/contexts/Pools/ActivePools/index.tsx
- src/contexts/Pools/BondedPools/index.tsx
- src/contexts/Pools/FavoritePools/defaults.ts
- src/contexts/Pools/FavoritePools/index.tsx
- src/contexts/Pools/FavoritePools/types.ts
- src/contexts/Pools/PoolsConfig/defaults.ts
- src/contexts/Pools/PoolsConfig/index.tsx
- src/contexts/Pools/PoolsConfig/types.ts
- src/contexts/Validators/types.ts
- src/library/Hooks/useCreatePoolAccounts/index.tsx
- src/library/ListItem/Labels/FavoritePool.tsx
- src/modals/UnlockChunks/Forms.tsx
- src/pages/Pools/Home/Favorites/index.tsx
- src/pages/Pools/Home/index.tsx
Moves pool account creation to a hook and renames `PoolsConfig` to `FavoritePools`.
> feat(refactor): create pool accounts to hooks

- src/canvas/PoolMembers/Lists/FetchPage.tsx
- src/contexts/Plugins/index.tsx
- src/hooks/useSubscanData/index.tsx
- src/modals/ClaimPayouts/Forms.tsx
- src/static/SubscanController/index.ts
- src/static/SubscanController/types.ts
Persists subscan results to `SubscanController` to prevent re-fetching the same request during a visit. (does not persist to local storage so results still need to be re-fetched on subsequent page visits).
> feat(refactor): persist Subscan results to class

- src/canvas/PoolMembers/Lists/Member.tsx
- src/contexts/Menu/defaults.ts
- src/contexts/Menu/index.tsx
- src/contexts/Menu/types.ts
- src/library/ListItem/Wrappers.ts
- src/library/Menu/List.tsx
- src/library/Menu/index.tsx
- src/library/Pool/index.tsx
- src/library/ValidatorList/ValidatorItem/Default.tsx
This PR iterates on `MenuProvider`, which relies on the mouse position when opening a floating menu. Context API has been tidied up and simplified. The menu now takes an arbitrary `ReactNode` instead of an opinionated list of `MenuItem`s.
> feat(refactor): Menu refresh with mouse-based position

- src/modals/Connect/Utils.ts
- src/modals/Connect/index.tsx
- src/types.ts
If the dashboard is currently being used in SubWallet Mobile, the SubWallet extension is prioritised at the top of connect options, and the rest of the web extensions are removed.
> feat(ux): Check SubWallet Mobile and filter Subwallet extension

- src/modals/Connect/index.tsx
Updated:
- Fix issue can not detect SubWallet in SubWallet Mobile
- Hide `developerTools` in SubWallet Mobile
Demo link:
https://sw-staking-demo.pages.dev/
Tested on:
Desktop Browser:
Mobile Browser:
SubWallet Mobile:
Nova:
> feat(ux): Update detect SubWallet in SubWallet in-app browser (#1983)

- src/contexts/FastUnstake/index.tsx
Changes fast unstake subscription logic to subscribe to the queue regardless of account status. Fixes an edge case where subscriptions would not initialise.
> fix: simplify fast unstake subscription

- src/hooks/useActiveBalances/index.tsx
- src/library/WithdrawPrompt/index.tsx
- src/locale/cn/modals.json
- src/locale/en/modals.json
- src/modals/Accounts/index.tsx
- src/pages/Nominate/Active/index.tsx
- src/pages/Pools/Home/index.tsx
Introduces a prompt on the Nominate and Pools page if there are unlock chunks active for an account.
This prompt does not display on the Pools page if the pool is being destroyed, as there is a dedicated prompt to manage that process.
Also touches the account list and useActiveBalance useEffect hooks to fix re-rendering issues.
> feat(ux): Add dedicated withdraw prompt for active unlock chunks

- src/static/BalancesController/index.ts
Fixes an issue where BalancesController sometimes would call unsub on a non-existing key.
> fix: check BalancesController unsub before calling

- src/config/networks.ts
Removes Parity RPC endpoint from westend network config.
> feat: Remove Parity RPC endpoint from westend

- src/contexts/FastUnstake/index.tsx
Fixes a fast unstake eligibility check by allowing users to register based on whether they are still bonded. The previous checks assumed users still had to be nominating, which is not the correct assumption; a user simply has to be bonded to assume that they may have been nominating at some previous era.
> fix: fast unstake eligibility based on bonding, not nominating

- src/controllers/SubscanController/index.ts
- Fixes an issue where title formatting attempted to retrieve data from empty filtered payouts.
- Fixes an issue where payout items from Subscan with an empty `account` field were displayed.
> fix: Misc Subscan payout fixes

- src/controllers/SubscanController/index.ts
- src/controllers/SubscanController/types.ts
Fixes an issue where incorrect unclaimed payouts fetched from Subscan were being displayed in payout graphs. Additional filters have been introduced to check if `unclaimedPayouts` records for a stash, with a validator, at an era, have already been included in `payouts`.
> fix: Fix errornous unclaimed payouts from Subscan

- src/canvas/PoolMembers/Lists/FetchPage.tsx
- src/canvas/PoolMembers/Lists/types.ts
- src/canvas/PoolMembers/Members.tsx
- src/contexts/Pools/ActivePool/defaults.ts
- src/contexts/Pools/ActivePool/index.tsx
- src/contexts/Pools/ActivePool/types.ts
- src/controllers/SubscanController/index.ts
- src/controllers/SubscanController/types.ts
- src/pages/Pools/Home/PoolStats/index.tsx
No longer uses Subscan's pool details endpoint for member counters, and uses `bondedPool.memberCounter` instead as it is now live on all networks. Saves Subscan calls and prevents the need to sync an additional call.
> feat: use `bondedPool.memberCounter`, deprecate `nomination_pool/pool` Subscan call

- src/library/List/SearchInput.tsx
- src/library/List/types.ts
- src/library/PoolList/Default.tsx
- src/library/ValidatorList/index.tsx
What does this PR fix?
Check the recording video. The search bar input value is not set correctly after switching back to back different tabs/pages.
https://github.com/paritytech/polkadot-staking-dashboard/assets/51565705/eb9783c6-f621-47b7-8d82-c7c296a18993
> fix: Search bar initial value on Pools/Validators page

- src/canvas/JoinPool/Preloader.tsx
- src/canvas/JoinPool/Wrappers.ts
- src/canvas/JoinPool/index.tsx
- src/canvas/JoinPool/types.ts
- src/contexts/Pools/JoinPools/index.tsx
- src/kits/Buttons/ButtonTab.tsx
- src/kits/Buttons/index.scss
- src/kits/Structure/PageTitleTabs/index.tsx
- src/kits/Structure/PageTitleTabs/types.ts
- src/library/CallToAction/index.tsx
- src/library/Loader/Wrappers.ts
- src/library/PoolSync/Loader.ts
- src/library/PoolSync/index.tsx
- src/pages/Pools/Home/Status/NewMember.tsx
Improves pool joining UX by opening the JoinPool canvas immediately and displaying a preloading state within the canvas. This prevents the user having to click the "Join Pool" button twice, once to initiate the syncing process, and another time to open the canvas. 
The user is still free to close the JoinPool canvas while the performance data is being fetched - it will continue and be ready when the user opens it again.
> feat: Open `JoinPool` canvas immediately,  preloader, prioritise low member pools.

- src/canvas/JoinPool/index.tsx
- src/contexts/Balances/index.tsx
- src/contexts/Pools/ActivePool/index.tsx
- src/contexts/Pools/JoinPools/index.tsx
- src/contexts/Staking/index.tsx
- src/controllers/ActivePoolsController/index.ts
- src/controllers/ActivePoolsController/types.ts
- src/hooks/useActivePools/index.tsx
- src/hooks/useActivePools/types.ts
- src/library/Nominations/index.tsx
- src/modals/AccountPoolRoles/index.tsx
- src/pages/Pools/Home/ManagePool/index.tsx
- src/pages/Pools/Home/index.tsx
Refector to persist all imported accounts active pools, to prevent re-syncing on account switching.
> feat(refactor): Persist all imported accounts active pools.

- src/canvas/JoinPool/Overview/PerformanceGraph.tsx
- src/canvas/JoinPool/Overview/Stats.tsx
- src/canvas/JoinPool/index.tsx
- src/canvas/JoinPool/types.ts
- src/library/PoolSync/Loader.ts
When a poolId is provided for the `JoinPool` canvas, the preloading is skipped, and instead a syncing label is shown alongside an empty graph while the performance data is being synced.
Note that this is not possible upon auto selection as post processing needs to be done to determine the selected pools.
> feat(ux):`JoinPool`:  Inline sync for provided pool

- src/contexts/Pools/PoolPerformance/types.ts
- src/library/List/defaults.ts
- src/library/ListItem/Labels/More.tsx
- src/library/ListItem/Labels/PoolBonded.tsx
- src/library/ListItem/Labels/PoolNominateStatus.tsx
- src/library/ListItem/Wrappers.ts
- src/library/Pool/index.tsx
- src/library/PoolList/index.tsx
This PR moves away from displaying a pool's reward graph directly in the pool list, in favour of syncing and displaying it in the `JoinPool` canvas as and when the user visits it.
Fetching performance data is slow, and carries performance issues when users browse the pool pages, of filter it in any way. To maintain performance and ease of use of the pool list, performance is no longer fetched when the list upates.
UI has been simplified, and amount of pools per page is now at 30, from 21.
> feat(ux): Simplify pool list, fetch performance on More click

- src/canvas/ManageNominations/index.tsx
"Revert Changes" is not working correctly in the Manage Nominations modal. The issue stems from both defaultNominations and newNominations pointing to the same memory. Consequently, when modifying newNominations, defaultNominations is also altered. As a result, clicking the "Revert Changes" button does not correctly revert the changes back.
https://github.com/paritytech/polkadot-staking-dashboard/blob/main/src/canvas/ManageNominations/index.tsx#L55-L64
> fix(manage-nominations): Revert changes behavior in Manage nominations

- src/pages/Nominate/Active/ManageBond.tsx
- src/pages/Overview/BalanceChart.tsx
https://github.com/paritytech/polkadot-staking-dashboard/issues/2072
> fix: Fix free balances (Overview & Nominate)

- src/config/networks.ts
- src/library/GenerateNominations/useFetchMethods.tsx
- src/library/ValidatorList/FilterValidators.tsx
- src/pages/Validators/AllValidators.tsx
This PR enables paged rewards on Kusama, and disables the "missing identity" filter as the People chain is now hosting identities on both Westend and Kusama.
Missing Identities will be re-introduced once the People system chain is supported.
> feat: Enable paged rewards on Kusama, disable `missing_identity`

- package.json
- src/hooks/useBuildPayload/index.tsx
- src/hooks/useSubmitExtrinsic/index.tsx
- yarn.lock
Bumps `@polkadot/api` and adds `withSignedTransaction: true` to `useBuildPayload`.
Does not yet deprecate the Kusama app. Future PR will add UI prompts for this.
> feat: New ledger app tx support

- src/consts.ts
- src/contexts/Validators/ValidatorEntries/index.tsx
- src/controllers/ActivePoolsController/index.ts
This PR disables identity fetches on westend and kusama, in preparation to using the People Chain instead. The changes here will fix an issue where Kusama nomination pools were not being updated.
> feat(refactor): disable identities on networks where People Chain is being used

- src/controllers/SubscanController/index.ts
No longer submits Subscan API key on requests, falling back to the default behaviour of 2 requests per IP address.
> feat(refactor) Remove Subscan API key

- package.json
- src/contexts/LedgerHardware/index.tsx
- yarn.lock
Fails the "runtime check" stage of a Ledger device if the Polkadot Ledger app version is not at least the version when generic support was introduced.
Uses `compare-versions` for semVer comparison.
> feat: Check if Polkadot app is at least generic version

- src/consts.ts
Disables identities on the Polkadot Relay Chain as identities are migrated. A future PR will add identities support back via the People system chain.
> feat(refactor): People chain on Polkadot - disable identities on Relay Chain

- src/config/networks.ts
- src/contexts/Api/defaults.ts
- src/contexts/Api/index.tsx
- src/contexts/Api/types.ts
- src/contexts/Pools/PoolPerformance/index.tsx
- src/contexts/Staking/index.tsx
A sufficient amount of eras have now passed to no longer consider the legacy `erasStakers` storage that was used prior to paged rewards. Cleans the codebase of pre-paged rewards code, and removes logic pertaining to the deprecation.
> feat(refactor): Remove pre-paged rewards deprecation logic

- src/library/CallToAction/index.tsx
- src/library/ListItem/Wrappers.ts
- src/library/Pool/index.tsx
- src/locale/cn/pages.json
- src/locale/en/pages.json
- src/pages/Pools/Home/Status/NewMember.tsx
- Small changes to pool item UI to simplify its layout.
- Adds Browse Pools button to pools Overview on inactive pool status.
> feat: simplify pool item UI

- src/contexts/Connect/OtherAccounts/index.tsx
Fixes an issue where an account imported via `OtherAccountsProvider` would also be imported in a web extension after the fact, resulting in a duplicate entry. Dashboard will now remove duplicate entries from `OtherAccounts`.
> fix: other account duplicate when added to extension

- src/canvas/JoinPool/Overview/PerformanceGraph.tsx
- src/contexts/UI/index.tsx
- src/contexts/UI/types.ts
- src/hooks/useSize/index.tsx
- src/modals/ValidatorGeo/index.tsx
- src/modals/ValidatorMetrics/index.tsx
- src/pages/Overview/Payouts.tsx
- src/pages/Payouts/index.tsx
This PR refines the `useSize` custom React hook, which tracks the width and height of a specified HTML element, updating dynamically when an outer element (or window, by default) resizes.
> feat(refactor): Generalise `useSize` hook

- src/contexts/Api/defaults.ts
- src/contexts/Api/index.tsx
- src/contexts/Api/types.ts
- src/model/Observables/ChainSpec.ts
- src/model/Query/NetworkMeta/index.ts
- src/model/Subscribe/StakingMetrics/index.ts
- src/pages/Nominate/Active/Stats/ActiveNominators.tsx
`maxElectingVoters` has been discontinued on chain, now nominators are uncapped, and `counterForNominators` is being used as the upper nominator limit in the dashboard.
> feat: Replace `maxElectingVoters` const with `counterForNominators` storage

- src/hooks/useEraTimeLeft/index.tsx
- src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
Fixes an issue where the end time of a timeleft UI would not re-render when the end time updates.
> feat(fix): Render timeleft on `end` time update

- src/hooks/useTimeLeft/index.tsx
- src/hooks/useTimeLeft/types.ts
- src/library/Utils/index.ts
- src/modals/UnlockChunks/Chunk.tsx
- src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
Abstracts `useTimeleft` function to be re-usable outside of staking dashboard environment.
> feat(refactor): Abstract `useTimeleft`

- packages/app/src/contexts/Payouts/index.tsx
Fixes and issue where  unclaimed payouts as floats were being passed into `unitToPlank`, resulting in a zero value.
> feat(fix): Ensure unclaimed payouts are ints

- packages/app/src/overlay/modals/ManagePool/Forms/ManageCommission/provider/index.tsx
In [Dashboard ](https://staking.polkadot.cloud/#/pools) when open pools and clic to Manage, this error occurs:
`hook.js:608 TypeError: ((intermediate value)(intermediate value)(intermediate value) || "100%").slice is not a function
at vpt (index-DX-H3mSL.js:7177:1080)
at S0 (index-DX-H3mSL.js:2427:17990)
at vS (index-DX-H3mSL.js:2429:45437)
at pS (index-DX-H3mSL.js:2429:41047)
at jk (index-DX-H3mSL.js:2429:40975)
at wy (index-DX-H3mSL.js:2429:40826)
at o3 (index-DX-H3mSL.js:2429:37070)
at fS (index-DX-H3mSL.js:2429:37880)
at Xd (index-DX-H3mSL.js:2427:3290)
at index-DX-H3mSL.js:2429:35370`
And appear a modal with this message: `Oops, Something Went Wrong
Click to reload`
For prevent this error, I fix the line 41 in `polkadot-staking-dashboard/packages/app/src/overlay/modals/ManagePool/Form …
> fix: Manage pools formatting error

- packages/app/src/contexts/Pools/ActivePool/defaults.ts
- packages/app/src/contexts/Pools/ActivePool/index.tsx
- packages/app/src/contexts/Pools/ActivePool/types.ts
- packages/app/src/library/CallToAction/index.tsx
- packages/app/src/library/SideMenu/Main.tsx
- packages/app/src/library/StatusLabel/index.tsx
- packages/app/src/overlay/canvas/JoinPool/Overview/index.tsx
- packages/app/src/pages/Nominate/Active/Status/NewNominator.tsx
- packages/app/src/pages/Nominate/Active/Status/NominationStatus.tsx
- packages/app/src/pages/Overview/Payouts/index.tsx
- packages/app/src/pages/Overview/StakeStatus/Tips/index.tsx
- packages/app/src/pages/Overview/StakeStatus/index.tsx
- packages/app/src/pages/Payouts/index.tsx
- packages/app/src/pages/Pools/Status/MembershipStatus.tsx
- packages/app/src/pages/Pools/Status/NewMember.tsx
- packages/app/src/pages/Pools/Status/index.tsx
- packages/locales/src/resources/cn/pages.json
- packages/locales/src/resources/en/pages.json
- packages/ui-buttons/tsconfig.json
- packages/ui-structure/src/RowSection/index.module.scss
- packages/ui-structure/src/RowSection/index.tsx
- packages/ui-structure/src/RowSection/types.ts
- packages/ui-structure/tsconfig.json
- tsconfig.json
Disables dual staking: 
- If in a pool, app will disable nominator setup for the active account.
- If a nominator, app will disable pool joining and creation for the active account.
- Stake Status (top of overview) has been amended to not display the inactive type of staking when the other is active.
- Added nominator / pool status messages when already staking via the other method.
> feat: Disable dual staking

- packages/app/src/api/runtimeApi/poolBalanceToPoints.ts
- packages/app/src/api/tx/poolUnbond.ts
- packages/app/src/controllers/Subscan/index.ts
- packages/app/src/overlay/canvas/PoolMembers/Lists/Member.tsx
- packages/app/src/overlay/canvas/PoolMembers/Prompts/UnbondMember.tsx
- packages/app/src/overlay/modals/ManagePool/Forms/LeavePool/index.tsx
- packages/app/src/overlay/modals/Unbond/index.tsx
- Uses the `balanceToPoints` runtime API when unbonding.
- Refers to active pool member points when leaving a pool or unbonding for a member.
- Fixes a Subscan issue where last member was getting cut from pool member results.
> feat: Use pool points for unbonding / leaving pool

- packages/app/src/contexts/Balances/index.tsx
- packages/app/src/contexts/Pools/ActivePool/index.tsx
- packages/app/src/overlay/index.tsx
- packages/app/src/overlay/modals/LeavePool/index.tsx
- packages/app/src/overlay/modals/ManagePool/Forms/LeavePool/index.tsx
- packages/app/src/pages/Pools/ClosurePrompts.tsx
- packages/locales/src/resources/en/pages.json
Fixes an issue where the depositor could not unbond the full amount when destroying a pool.
> feat(fix): Abstract `LeavePool`, use as depositor unbond

- README.md
- packages/app/src/api/txSubmission.ts
- packages/app/src/api/types.ts
- packages/app/src/contexts/Balances/types.ts
- packages/app/src/contexts/TxMeta/index.tsx
- packages/app/src/hooks/useActiveBalances/index.tsx
- packages/app/src/hooks/useSubmitExtrinsic/index.tsx
- packages/app/src/library/Headers/Sync.tsx
- packages/app/src/library/SubmitTx/Default.tsx
- packages/app/src/library/SubmitTx/ManualSign/Ledger/Submit.tsx
- packages/app/src/library/SubmitTx/ManualSign/Ledger/index.tsx
- packages/app/src/library/SubmitTx/ManualSign/Vault/index.tsx
- packages/app/src/library/SubmitTx/ManualSign/WalletConnect/index.tsx
- packages/app/src/library/SubmitTx/ManualSign/index.tsx
- packages/app/src/library/SubmitTx/index.tsx
- packages/app/src/library/SubmitTx/types.ts
- packages/app/src/overlay/modals/ManageFastUnstake/index.tsx
- Refactors tx submission to be more readable. 
- Calculates nonce based on pending txs, allowing multiple txs to be submitted per block.
- Fixes an issue where multiple "in block" notifications would be delivered erroneously.
> feat: Tx subscriptions to `TxSubmission`

- packages/app/src/Router.tsx
- packages/app/src/StakingApi/FastUnstakeApi.tsx
- packages/app/src/StakingApi/UnclaimedRewardsApi.tsx
- packages/app/src/StakingApi/index.tsx
- packages/app/src/StakingApi/types.ts
- packages/app/src/contexts/FastUnstake/defaults.ts
- packages/app/src/contexts/FastUnstake/index.tsx
- packages/app/src/contexts/FastUnstake/types.ts
- packages/app/src/contexts/Validators/Utils.ts
- packages/app/src/hooks/useUnstaking/index.tsx
- packages/app/src/overlay/modals/ManageFastUnstake/index.tsx
- packages/app/src/pages/Nominate/Active/Status/NominationStatus.tsx
- packages/app/src/pages/Nominate/Active/index.tsx
- packages/app/src/workers/stakers.ts
- packages/app/src/workers/types.ts
- packages/locales/src/resources/cn/library.json
- packages/locales/src/resources/en/library.json
- packages/plugin-staking-api/src/index.tsx
- packages/plugin-staking-api/src/queries/useCanFastUnstake.tsx
- packages/plugin-staking-api/src/types.ts
Determines whether nominators can fast unstake via Staking API call `canFastUnstake`, and discontinues legacy era stakers scraping from the node.
> feat: Use `useCanFastUnstake` query

- packages/app/src/Router.tsx
- packages/app/src/StakingApi/index.tsx
- packages/app/src/controllers/Subscan/index.ts
- packages/app/src/library/Graphs/EraPoints.tsx
- packages/app/src/library/Graphs/types.ts
- packages/app/src/library/MainFooter/TokenPrice.tsx
- packages/app/src/overlay/modals/ValidatorMetrics/ActiveGraph.tsx
- packages/app/src/overlay/modals/ValidatorMetrics/index.tsx
- packages/app/src/pages/Overview/AccountBalance/FiatValue.tsx
- packages/app/src/pages/Overview/Payouts/ActiveGraph.tsx
- packages/app/src/pages/Payouts/ActiveGraph.tsx
- packages/plugin-staking-api/src/index.tsx
- packages/plugin-staking-api/src/queries/useValidatorEraPoints.tsx
- packages/plugin-staking-api/src/types.ts
- Replaces Subscan validator era points fetching with Staking API.
- Opts for one global `<ApolloProvider>` that is not removed on plugin toggling.
> feat(refactor): Use Staking API for validator era points

- packages/styles/theme/index.scss
- packages/ui-core/src/modal/Close/index.module.scss
Minor CSS tweak fixing https://github.com/polkadot-cloud/polkadot-staking-dashboard/issues/2419
Manually tested in latest Firefox and Chromium.
> fix: improve `color` contrast for dark theme button

- packages/app/src/App.tsx
- packages/app/src/Themes.tsx
- packages/app/src/common-types.ts
- packages/app/src/config/networks.ts
- packages/app/src/contexts/ThemeValues/defaults.ts
- packages/app/src/contexts/ThemeValues/index.tsx
- packages/app/src/contexts/ThemeValues/types.ts
- packages/app/src/contexts/Themes/defaults.ts
- packages/app/src/contexts/Themes/index.tsx
- packages/app/src/contexts/Themes/types.ts
- packages/app/src/library/Graphs/AveragePayoutLine.tsx
- packages/app/src/library/Graphs/EraPointsLine.tsx
- packages/app/src/library/Graphs/GeoDonut.tsx
- packages/app/src/library/Graphs/PayoutBar.tsx
- packages/app/src/library/Graphs/PayoutLine.tsx
- packages/app/src/library/PoolList/index.tsx
- packages/app/src/library/ValidatorList/index.tsx
- packages/app/src/library/WithdrawPrompt/index.tsx
- packages/app/src/overlay/canvas/PoolMembers/Members.tsx
- packages/app/src/pages/Nominate/Active/CommissionPrompt.tsx
- packages/app/src/pages/Nominate/Active/UnstakePrompts.tsx
- packages/app/src/pages/Payouts/PayoutList/index.tsx
- packages/app/src/pages/Pools/ClosurePrompts.tsx
- packages/styles/accents/kusama.scss
- packages/styles/accents/polkadot.scss
- packages/styles/accents/westend.scss
- packages/styles/theme/theme.scss
- packages/ui-buttons/src/ButtonPrimaryInvert/index.module.scss
- packages/ui-buttons/src/ButtonSubmitInvert/index.module.scss
- packages/ui-core/src/base/Entry/index.tsx
Enhances and simplifies the codebase, iterating theming and allowing more intelligent theme solutions.
> feat(ux): Get theme values directly from CSS, discontinue network colors

- packages/app/src/StakingApi/FastUnstakeApi.tsx
- packages/app/src/StakingApi/UnclaimedRewardsApi.tsx
- packages/app/src/overlay/canvas/Pool/Overview/Performance/ActiveGraph.tsx
- packages/app/src/overlay/canvas/ValidatorMetrics/EraPoints/ActiveGraph.tsx
- packages/app/src/overlay/canvas/ValidatorMetrics/Rewards/ActiveGraph.tsx
- packages/app/src/pages/Overview/Payouts/ActiveGraph.tsx
- packages/app/src/pages/Payouts/ActiveGraph.tsx
- packages/plugin-staking-api/src/queries/activeValidatorRanks.tsx
- packages/plugin-staking-api/src/queries/canFastUnstake.tsx
- packages/plugin-staking-api/src/queries/poolCandidates.tsx
- packages/plugin-staking-api/src/queries/poolEraPoints.tsx
- packages/plugin-staking-api/src/queries/poolRewards.tsx
- packages/plugin-staking-api/src/queries/rewards.tsx
- packages/plugin-staking-api/src/queries/unclaimedRewards.tsx
- packages/plugin-staking-api/src/queries/validatorEraPoints.tsx
- packages/plugin-staking-api/src/queries/validatorEraPointsBatch.tsx
- packages/plugin-staking-api/src/queries/validatorRewards.tsx
Staking API queries are now using a `network` argument instead of a `chain` argument.
> feat(refactor):  Staking API arg `chain` -> `network`

- packages/app/src/library/SideMenu/Wrapper.ts
- packages/app/src/library/SideMenu/index.tsx
In preparation of re-purposing the bottom left section of the side menu, the menu minimise toggle has been moved to the top of the menu to accompany the cloud icon, forming one large button.
> feat(ux): Amend side menu toggle to top of menu

- packages/app/src/common-types.ts
- packages/app/src/library/SideMenu/Main.tsx
- packages/app/src/library/SideMenu/Primary/Wrappers.ts
- packages/app/src/library/SideMenu/Primary/index.tsx
- packages/app/src/library/SideMenu/Secondary/Wrappers.ts
- packages/app/src/library/SideMenu/Secondary/index.tsx
- packages/app/src/library/SideMenu/Wrapper.ts
- packages/app/src/library/SideMenu/index.tsx
- packages/app/src/library/SideMenu/types.ts
- packages/consts/src/index.ts
- packages/styles/theme/_variables.scss
- packages/ui-core/src/base/Page/Side/index.module.scss
- packages/ui-core/src/base/Page/Side/index.tsx
- packages/ui-core/src/base/Page/Side/types.ts
Shrinks the maximised side menu to give more space to the main app content. Refactors props such as `action`, which is now simply `bullet`, and unified some styles.
The side menu, when hidden & toggle-able, retains its previous width of 195px.
> feat(ux): Shrink maximised side menu

- package.json
- packages/ui-core/package.json
- packages/ui-core/src/popover/ConnectItem/Container/index.module.scss
- packages/ui-core/src/popover/ConnectItem/Container/index.tsx
- yarn.lock
Introduces `SimpleBar` to the codebase, adding it to the connect popover container, allowing a unified scroll bar style that automatically hides on all browsers and platforms. 
Prevents scroll bars from being displayed when external trackpads or mice are connected.
> feat(ux): use SimpleBar in Connect Container

- packages/app/src/overlay/modals/SelectCurrency/index.tsx
- Added sorting in the SelectCurrency modal to display currencies alphabetically based on translated names. Using localeCompare() with the user's current language settings ensures proper alphabetical ordering regardless of whether the interface is in English, Spanish, or Chinese.
> Fix: Currency in modal order

- packages/app/src/pages/Nominate/Active/Stats/MinimumActiveStake.tsx
Amends the minimum to earn rewards stat to be at least the minimum nominator bond.
> fix: Minimum to earn rewards to be at least min nominator bond

- packages/consts/src/networks.ts
- packages/consts/src/util.ts
- packages/dedot-api/src/services/kusama.ts
- packages/dedot-api/src/services/polkadot.ts
- packages/dedot-api/src/services/westend.ts
- packages/dedot-api/src/start.ts
- packages/dedot-api/src/types/index.ts
- packages/dedot-api/src/types/serviceDefault.ts
- packages/global-bus/src/networkConfig/util.ts
- packages/types/src/networks.ts
Adds support for Asset Hub chains on Polkadot, Kusama and Westend. Services now connect to the hub as an additional chain, and populates metadata like chain specs and imported account balances from the chain.
> feat: Add AssetHub chains to `dedot-api` default services

- packages/app/src/contexts/Network/index.tsx
- packages/app/src/overlay/modals/Networks/index.tsx
- packages/consts/package.json
- packages/consts/src/networks.ts
- packages/consts/src/util.ts
- packages/consts/tsconfig.json
- packages/global-bus/src/networkConfig/util.ts
- packages/locales/package.json
- packages/locales/tsconfig.json
- pnpm-lock.yaml
Adds the ability to disable networks in a production environment.  Disabled Westend in preparation for the AssetHub migration.
> feat: Disable Westend in production - Prep for AssetHub Migration

- packages/app/tsconfig.json
- packages/assets/tsconfig.json
- packages/dedot-api/tsconfig.json
- packages/global-bus/tsconfig.json
- packages/locales/tsconfig.json
- packages/plugin-staking-api/tsconfig.json
- packages/rpc-config/tsconfig.json
- packages/types/tsconfig.json
- packages/ui-buttons/tsconfig.json
- packages/ui-core/tsconfig.json
- packages/ui-graphs/tsconfig.json
- packages/ui-identity/tsconfig.json
- packages/ui-overlay/tsconfig.json
- packages/utils/tsconfig.json
- tsconfig.base.json
- tsconfig.json
- tsconfig.react.json
Minimising tsconfig.json configs by creating reusable tsconfig files.
- Created [tsconfig.base.json](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) (core options) and [tsconfig.react.json](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) (adds JSX support) in the root.
- All package configs now extend one of these, keeping only package-specific overrides (like types, include, or baseUrl).
- The root [tsconfig.json](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) is now minimal and extends the base config. …
> feat(refactor): Optimise tsconfigs

- package.json
- packages/app/package.json
- packages/assets/package.json
- packages/consts/package.json
- packages/dedot-api/package.json
- packages/global-bus/package.json
- packages/locales/package.json
- packages/plugin-staking-api/package.json
- packages/rpc-config/package.json
- packages/styles/package.json
- packages/tests/package.json
- packages/types/package.json
- packages/ui-buttons/package.json
- packages/ui-core/package.json
- packages/ui-core/src/popover/MenuItem/index.module.scss
- packages/ui-graphs/package.json
- packages/ui-overlay/package.json
- packages/utils/package.json
- pnpm-lock.yaml
This PR refactors the build process by switching to the Polkicon tsup build and updating various script commands. It also updates the "@w3ux/react-polkicon" dependency version and adjusts several package.json clear scripts to include deletion of node_modules.
- Updated clear scripts in multiple package.json files to remove node_modules along with build artifacts.
- Upgraded "@w3ux/react-polkicon" from ^3.2.1 to ^3.2.6 across affected packages.
- Modified the test script in packages/tests to run "vitest run" for improved consistency.
> feat(refactor) Use Polkicon `tsup` build, misc script amendments

- packages/app/src/contexts/EraStakers/defaults.ts
- packages/app/src/contexts/EraStakers/index.tsx
- packages/app/src/contexts/EraStakers/types.ts
- packages/app/src/pages/Validators/Stats/ActiveValidators.tsx
- packages/app/src/workers/stakers.ts
- packages/app/src/workers/types.ts
Amends active validator logic by not counting exposures through the worker, but simply to refer to exposure length. This old logic was an artefact of when active validators had to be determined via the worker.
> chore: active validators optimisation

- packages/app/src/pages/Nominate/Active/ManageBond.tsx
Fixed logic in ManageBond.tsx that previously required users to be actively nominating to access unbond/unstake actions.
Now, any user with bonded nominator funds can unbond, regardless of whether they are currently nominating or have stopped nominating.
This resolves issues for users who:
- Have stopped nominating but still have bonded funds.
- Are in a pool but have leftover nominator funds (dual staking cleanup).
> fix: allow unbond/unstake for any user with bonded funds, not just active nominators

- packages/app/src/library/WithdrawPrompt/index.tsx
Remove UI restriction that prevented users from accessing withdrawal of unbonded stake when pools are in the 'Destroying' state.
Users can now always withdraw completed unbonding periods regardless of pool status. This aligns the UI with expected blockchain behaviour and resolves the issue where users could not withdraw after the unbonding period if the pool was being destroyed.
> fix: allow withdrawals from destroying pools after unbonding period

- packages/app/src/contexts/EraStakers/defaults.ts
- packages/app/src/contexts/EraStakers/index.tsx
- packages/app/src/contexts/EraStakers/types.ts
- packages/app/src/pages/Nominate/Active/Stats/ActiveNominators.tsx
- packages/app/src/workers/stakers.ts
- packages/app/src/workers/types.ts
- packages/plugin-staking-api/src/index.ts
- packages/plugin-staking-api/src/queries/eraTotalNominators.ts
- packages/plugin-staking-api/src/types.ts
This PR optimizes the calculation of total nominator count by introducing a new API endpoint and refactoring the existing worker-based calculation. The changes aim to improve performance by fetching nominator counts from an external API when available, while maintaining backward compatibility.
Key changes:
- Introduces a new `eraTotalNominators` API query for optimized nominator count fetching
- Removes expensive nominator aggregation logic from the staking worker
- Updates context to use either API data or fallback to overview-based calculation
> feat(refactor): Total Nominator Count optimisations

- packages/app/package.json
- packages/app/src/library/Headers/Popovers/ConnectPopover/Wallets.tsx
- packages/dedot-api/package.json
- packages/global-bus/package.json
- pnpm-lock.yaml
This PR adds Mimir multisig wallet support to the staking dashboard by integrating it as a new connection option in the wallet selector.
- Upgraded w3ux packages to support Mimir integration
- Added Mimir wallet as a new multisig connection option in the wallet popover
- Updated dependencies to latest versions with Mimir support
> feat: Add Mimir connect option

- packages/app/src/contexts/UI/defaults.ts
- packages/app/src/contexts/UI/index.tsx
- packages/app/src/contexts/UI/util.ts
- packages/consts/src/index.ts
This PR implements functionality to persist and retrieve the active navigation section in local storage, allowing the application to remember the user's last visited section across browser sessions.
- Added local storage support for the `activeSection` state
- Introduced utility function to safely retrieve the initial active section from storage
- Updated the UI context to manage active section persistence with proper getter/setter pattern
> feat: get/set local `activeSection`

- packages/app/src/hooks/useBondActions/index.ts
- packages/app/src/hooks/useBondActions/types.ts
- packages/app/src/pages/Nominate/Active/ManageBond.tsx
This PR introduces a new `useBondActions` hook to centralize bond-related action logic and simplify the `ManageBond` component. The refactor consolidates complex conditional logic for determining when bonding, unbonding, unstaking, and fast unstaking actions are available.
- Consolidates bond action eligibility logic into a dedicated hook
- Reduces complexity in the ManageBond component by removing inline conditional logic
- Provides a cleaner API with boolean flags for each bond action
> feat(refactor): Introduce `useBondActions` hook, tidy up bond logic

- packages/app/src/contexts/FastUnstake/index.tsx
- packages/app/src/contexts/FastUnstake/types.ts
- packages/app/src/hooks/useBondActions/index.ts
- packages/app/src/modals/ManageFastUnstake/index.tsx
- packages/dedot-api/src/consts/fastUnstake.ts
- packages/dedot-api/src/consts/staking.ts
- packages/dedot-api/src/defaultService/baseService.ts
- packages/dedot-api/src/defaultService/subscriptionManager.ts
- packages/dedot-api/src/defaultService/types.ts
- packages/dedot-api/src/services/kusama.ts
- packages/dedot-api/src/services/polkadot.ts
- packages/dedot-api/src/services/westend.ts
- packages/dedot-api/src/subscribe/fastUnstakeConfig.ts
- packages/dedot-api/src/subscribe/fastUnstakeQueue.ts
- packages/dedot-api/src/subscribe/stakingMetrics.ts
- packages/dedot-api/src/tx/fastUnstakeDeregister.ts
- packages/dedot-api/src/tx/fastUnstakeRegister.ts
- packages/dedot-api/src/types/index.ts
- packages/global-bus/src/fastUnstakeConfig/default.ts
- packages/global-bus/src/stakingMetrics/default.ts
- packages/types/src/fastUnstake.ts
- packages/types/src/networks.ts
Prepares the codebase for Kusama AssetHub migration support.
- Updates Kusama's staking chain to `KusamaAssetHubApi`, updates apis being passed into api calls.
- Fast unstake stays on Kusama relay chain - a new `FastUnstakeChain` abstraction has been added.
- `FastUnstakeConsts` has been abstracted to fetch them from the correct chains per network.
- Added `fastUnstakeApi` to `SubscriptionManager` and fixed fast unstake queries.
- Moved fast unstake txs to `FastUnstakeChain`.
- `FastUnstakeConfigQuery ` takes FastUnstakeApi instead of `StakingApi`.
- Moved `erasToCheckPerBlock` to `FastUnstakeConfig`
> feat(refactor): Kusama asset hub migration

- packages/app/src/contexts/Plugins/index.tsx
- packages/app/src/library/Headers/Popovers/MenuPopover/index.tsx
- packages/app/src/modals/Plugins/index.tsx
- packages/consts/src/plugins.ts
- packages/consts/src/util/networks.ts
- packages/global-bus/src/plugins/index.ts
- packages/global-bus/src/plugins/local.ts
- packages/global-bus/src/plugins/private.ts
This PR introduces the ability to force disable plugins on a per-network basis, allowing specific plugins to be disabled for certain network configurations. This is particularly useful for handling cases where certain plugins may not be available or functional on specific networks.
Key changes:
- Added `DisabledPluginsPerNetwork` configuration to disable plugins by network
- Updated plugin loading logic to filter out disabled plugins per network
- Modified UI components to show disabled plugins as non-interactive
The Staking API is no longer supporting the Westend network, and is now disabled.
The Staking API has temporarily been disabled for Kusama while support for the Asset Hub migration is undergoing.
> feat: Force disable plugins per network, disable Staking API on Kusama, Westend
