polkadot-cloud/polkadot-staking-dashboard

public/index.html, src/constants.ts, src/contexts/Staking/index.tsx, src/library/List/index.ts, src/library/Validator/Wrapper.ts, src/library/Validator/index.tsx, src/library/ValidatorList/Filters/Wrapper.ts, src/library/ValidatorList/Filters/index.tsx, src/library/ValidatorList/index.tsx, src/pages/Stake/Setup/Summary/index.tsx
Some render optimisations, bug fixes and mobile support.
=> Bug Fixes + Optimizations

src/Wrappers.tsx, src/library/Headers/Wrappers.ts, src/library/PageTitle/index.tsx, src/library/Validator/Wrapper.ts
Simplifying the sticky header.
=> Makes Page Title Sticky CSS only

src/contexts/Pools/defaults.ts, src/contexts/Pools/index.tsx, src/modals/UpdateBond/PoolForms.tsx, src/modals/UpdateBond/StakeForms.tsx, src/modals/UpdateBond/index.tsx, src/pages/Pools/ManageBond.tsx, src/pages/Pools/index.tsx, src/pages/Stake/Active/ManageBond.tsx, tsconfig.json
This adds the bonded and active balance info for the active account  into Pool context, while trying to keep the whole bonding flow consistent with the staking bonds.
=> add manageBond for pools.

src/contexts/Balances/index.tsx, src/contexts/Connect.tsx, src/contexts/Staking/index.tsx, src/library/Account/index.tsx, src/library/Form/AccountDropdown/index.tsx, src/library/Form/AccountSelect/index.tsx, src/library/Hooks/useSubmitExtrinsic.tsx, src/modals/ConnectAccounts/Accounts.tsx, src/modals/ConnectAccounts/Extension.tsx, src/modals/ConnectAccounts/Extensions.tsx, src/modals/ConnectAccounts/Wallet.tsx, src/modals/ConnectAccounts/Wallets.tsx, src/modals/ConnectAccounts/Wrappers.ts, src/modals/ConnectAccounts/index.tsx, src/modals/Wrappers.ts, src/pages/Overview/ActiveAccount.tsx, src/pages/Overview/Payouts.tsx, src/pages/Payouts/index.tsx, src/pages/Stake/Active/Nominations/Wrapper.tsx, src/pages/Stake/Active/Nominations/index.tsx, src/pages/Stake/Setup/Summary/index.tsx
This PR fixes multi-pop up and tidies up some code.
=> Extensions multi Pop-up fix

src/contexts/Balances/index.tsx, src/types/balances.ts, src/types/index.ts
Fixes an issue that prevented bond updates upon submitted extrinsics. Ledgers need subscriptions for this to happen.
=> Rb test unbond all

src/contexts/Balances/index.tsx, src/contexts/Pools/index.tsx, src/library/Form/BondInput/index.tsx, src/library/Form/BondInputWithFeedback/index.tsx, src/modals/CreatePool/Forms.tsx, src/modals/JoinPool/Forms.tsx, src/modals/UpdateBond/PoolForms.tsx, src/modals/UpdateBond/StakeForms.tsx, src/pages/Overview/BalanceGraph.tsx, src/pages/Pools/ManageBond.tsx, src/pages/Stake/Setup/Bond/index.tsx
This PR fixes various things around pools and makes BondInput generic towards staking and pooling.
=> Rb pool forms fixes

src/contexts/Assistant.tsx
=> close assistant if def open

src/contexts/Balances/index.tsx, src/contexts/Connect.tsx, src/contexts/Staking/index.tsx, src/modals/ConnectAccounts/Accounts.tsx, src/types/balances.ts
WIP: evolving the account connect experience.
=> Accounts UI & Fixes

src/Utils.ts
this should fix the issues with digits followed by non-digit chars (e.g. 123hgjh).
=> fix input validation for mixed digits

src/contexts/Pools/ActivePool/index.tsx, src/contexts/Pools/BondedPools/index.tsx, src/contexts/Pools/PoolMemberships/index.tsx, src/contexts/Pools/PoolsConfig/index.tsx, src/contexts/SessionEra/defaults.ts, src/contexts/SessionEra/index.tsx, src/contexts/SessionEra/types.ts
=> Rb api fixes

src/contexts/Pools/PoolsConfig/defaults.ts, src/contexts/Pools/PoolsConfig/index.tsx, src/contexts/Pools/types.ts, src/library/ListItem/Labels/FavouritePool.tsx, src/library/ListItem/Labels/FavouriteValidator.tsx, src/library/Pool/index.tsx, src/library/PoolList/index.tsx, src/library/ValidatorList/Validator/Default.tsx, src/library/ValidatorList/Validator/Nomination.tsx, src/pages/Pools/Favourites/index.tsx, src/pages/Pools/index.tsx
=> Rb pool favourites

src/contexts/Pools/BondedPools/index.tsx, src/library/ListItem/Labels/NominationStatus.tsx, src/library/PoolList/index.tsx, src/pages/Pools/Home/PoolStats/Announcements.tsx, src/pages/Pools/Home/PoolStats/Header.tsx, src/pages/Pools/Home/PoolStats/Wrappers.ts, src/pages/Pools/Home/PoolStats/index.tsx, src/pages/Pools/Home/index.tsx
=> Nomination Pool additional support

src/library/Filter/LargeItem.tsx, src/library/Filter/context.tsx, src/library/Filter/types.ts, src/library/GenerateNominations/index.tsx, src/library/GenerateNominations/useFetchMethods.tsx, src/library/List/Selectable.tsx, src/library/List/index.ts, src/library/ListItem/Labels/EraStatus.tsx, src/library/ValidatorList/Filters.tsx, src/library/ValidatorList/index.tsx, src/pages/Nominate/Active/Nominations/index.tsx, src/pages/Overview/NetworkSats/Wrappers.ts
Adds one-click buttons to add nominations to a selection.
=> [WIP] One click add nominations

src/Wrappers.tsx, src/contexts/Validators/index.tsx, src/library/Button/index.tsx, src/library/Filter/Wrappers.ts, src/library/Form/Wrappers.ts, src/library/Headers/Wrappers.ts, src/pages/Community/Entity.tsx, src/pages/Community/List.tsx, src/pages/Nominate/Setup/Payee/Wrappers.tsx, src/pages/Nominate/Setup/index.tsx, src/pages/Pools/Create/index.tsx, src/theme/default.ts
Fixes issues around dark theming and some position discrepancies.
=> Theme amendments

src/contexts/Account/defaults.ts, src/contexts/Api/defaults.ts, src/contexts/Balances/defaults.ts, src/contexts/Connect/defaults.ts, src/contexts/Extrinsics/defaults.ts, src/contexts/Help/defaults.ts, src/contexts/Menu/defaults.ts, src/contexts/Modal/defaults.ts, src/contexts/Notifications/defaults.ts, src/contexts/Pools/ActivePools/defaults.ts, src/contexts/Pools/BondedPools/defaults.ts, src/contexts/Pools/PoolMembers/defaults.ts, src/contexts/Pools/PoolsConfig/defaults.ts, src/contexts/Staking/defaults.ts, src/contexts/Subscan/defaults.ts, src/contexts/Themes/defaults.ts, src/contexts/Tooltip/defaults.ts, src/contexts/TransferOptions/defaults.ts, src/contexts/TxFees/defaults.ts, src/contexts/UI/defaults.ts, src/contexts/Validators/defaults.ts, src/library/Filter/defaults.ts, src/library/PoolList/index.tsx, src/pages/Community/defaults.ts, src/pages/Overview/NetworkSats/Inflation.tsx, src/pages/Payouts/PayoutList/context.tsx, src/pages/Pools/Home/context.tsx
Fix some of the warnings that appeared during the build/start of the app
=> Fix various warnings

.github/dependabot.yml, .github/mergify.yml, .github/workflows/ci.yml
`.github/dependabot.yml`: checks for dependencies updates, and when it finds one it automatically opens a PR and adds the `automerge` label
`.github/mergify.yml`: Add some rules for auto-merging: 
a) needs at least 1 approval and there are no `changes requested` and 
b) must have the label `automerge`. 
PR that fulfills these 2 rules will merge automatically to master
=> Add dependabot and mergify CI scripts

src/library/ListItem/Labels/Identity.tsx, src/library/ListItem/Wrappers.ts, src/pages/Overview/NetworkSats/Announcements.tsx, src/pages/Overview/Tips/Wrappers.tsx, src/pages/Payouts/Wrappers.ts, src/theme/default.ts
=> Rb pre release polish

src/library/ListItem/Wrappers.ts, src/pages/Pools/Roles/index.tsx
- Fixes a flex wrap issue for pool IDs
- Fixes the re-fetching of account role metadata upon active pool switching.
=> Post release fixes

src/pages/Payouts/index.tsx
=> Fix payout dates

src/config/validators/index.ts
Dear team, 
Please consider this PR to make a correction in the url shown in the dashboard for Gatotech (forgot to add the `https://` prefix to the original entry, so it was not working).
.... and also took advantage of the opportunity and added a cat 😸 to the Name field :-D
Many thanks!!
**_Milos_**
=> Amend Gatotech's url

src/pages/Payouts/index.tsx
=> Add assignments in useEffects

src/contexts/TransferOptions/defaults.ts, src/contexts/TransferOptions/index.tsx, src/contexts/TransferOptions/types.ts, src/library/Form/Unbond/UnbondFeedback.tsx, src/library/Form/Unbond/UnbondInput.tsx, src/library/Form/types.ts, src/library/Graphs/Bonded.tsx, src/locale/cn/pages.json, src/locale/en/pages.json, src/modals/UpdateBond/Forms/UnbondAll.tsx, src/modals/UpdateBond/Forms/UnbondPoolToMinimum.tsx, src/modals/UpdateBond/Forms/UnbondSome.tsx, src/pages/Overview/BalanceGraph.tsx
=> Balances and Locks Amendments

src/consts.ts, src/locale/cn/base.json, src/locale/en/base.json, src/modals/UpdatePayee/index.tsx, src/pages/Nominate/Active/Status.tsx
Refactors `PayeeStatus` to make it more user friendly for translating.
=> refactor payeeStatus

src/locale/cn/pages.json, src/locale/en/pages.json, src/modals/UpdatePayee/index.tsx, src/pages/Nominate/Active/Controller/index.tsx, src/pages/Nominate/Active/ControllerNotImported.tsx, src/pages/Pools/Create/PoolName/Input.tsx, src/pages/Pools/Create/Summary/index.tsx, src/pages/Pools/Home/PoolStats/Announcements.tsx, src/pages/Pools/PoolAccount/index.tsx, src/pages/Pools/Roles/RoleEditInput/index.tsx
Update the pages session translation
=> Ting locale pages

src/library/ListItem/Labels/Blocked.tsx, src/library/ListItem/Labels/Commission.tsx, src/library/ListItem/Labels/CopyAddress.tsx, src/library/ListItem/Labels/EraStatus.tsx, src/library/ListItem/Labels/FavoritePool.tsx, src/library/ListItem/Labels/FavoriteValidator.tsx, src/library/ListItem/Labels/JoinPool.tsx, src/library/ListItem/Labels/Members.tsx, src/library/ListItem/Labels/Oversubscribed.tsx, src/library/ListItem/Labels/ParaValidator.tsx, src/library/ListItem/Labels/PoolBonded.tsx, src/library/ListItem/Labels/PoolId.tsx, src/library/ListItem/Labels/PoolMemberBonded.tsx, src/library/NetworkBar/Status.tsx, src/library/NetworkBar/index.tsx, src/locale/cn/library.json, src/locale/en/library.json
Adding 4nd part of the library translation
=> library translation p4

src/contexts/Api/index.tsx, src/types/index.ts
Edited the NetworkName and removed Toggle as it's not be used
=> Edited 2 enums

.licenserc.json, .prettierrc.js, .scripts/localeOrderKeys.js, .scripts/localeValidate.js, .scripts/utils.js
Does what the title says.
#513
=> Refactor scripts, add key ordering to validate

src/Providers.tsx, src/Router.tsx, src/config/networks.ts, src/contexts/Api/index.tsx, src/contexts/Connect/Utils.ts, src/contexts/Connect/index.tsx, src/contexts/FastUnstake/index.tsx, src/contexts/Pools/PoolsConfig/index.tsx, src/contexts/Setup/index.tsx, src/contexts/Validators/index.tsx, src/library/Form/Dropdown/index.tsx, src/library/Hooks/useTimeLeft/index.tsx, src/library/Hooks/useTimeLeft/types.ts, src/library/NetworkBar/index.tsx, src/library/SideMenu/index.tsx, src/modals/Networks/index.tsx, src/pages/Community/Entity.tsx, src/pages/Community/Item.tsx, src/pages/Community/List.tsx, src/pages/Nominate/Active/Status.tsx, src/pages/Overview/BalanceChart.tsx, src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
=> Lowercase the network names

src/Wrappers.tsx, src/contexts/Extensions/index.tsx, src/library/Account/Wrapper.ts, src/library/Filter/Wrappers.ts, src/library/Graphs/Wrappers.ts, src/library/Headers/Wrappers.ts, src/library/List/index.ts, src/library/ListItem/Wrappers.ts, src/library/Modal/Wrappers.tsx, src/library/NetworkBar/Wrappers.ts, src/library/Overlay/Wrappers.tsx, src/library/PoolAccount/Wrapper.ts, src/library/StatBoxList/Wrapper.ts, src/library/StatusLabel/Wrapper.ts, src/locale/cn/modals.json, src/locale/en/modals.json, src/modals/ConnectAccounts/Extension.tsx, src/modals/ConnectAccounts/Extensions.tsx, src/modals/ConnectAccounts/Wrappers.ts, src/modals/ManagePool/Wrappers.ts, src/modals/UnlockChunks/Wrappers.ts, src/modals/Wrappers.ts, src/pages/Overview/NetworkSats/Wrappers.ts, src/pages/Overview/StakeStatus/Tips/Wrappers.tsx, src/pages/Overview/StakeStatus/Tips/index.tsx, src/pages/Overview/StakeStatus/Wrappers.tsx, src/pages/Overview/Wrappers.ts, src/pages/Pools/Home/PoolStats/Wrappers.ts
=> flex & extension tidy up

src/library/Hooks/useFillVariables/index.tsx, src/pages/Overview/NetworkSats/Announcements.tsx
Capitalised NETWORK_NAME in help session and others
=> Capitalize network name

src/Utils.ts, src/library/Hooks/useNominationStatus/index.tsx, src/modals/StartStaking/index.tsx, src/pages/Nominate/Setup/index.tsx
Nominator setup supports going back to Overview if user landed there from Start Staking CTA.
=> CTA back to overview link

src/config/pages.ts, src/pages/Community/index.tsx, src/pages/Favorites/index.tsx, src/pages/Nominate/index.tsx, src/pages/Overview/BalanceChart/BarSegment.tsx, src/pages/Overview/BalanceChart/LegendItem.tsx, src/pages/Overview/BalanceChart/Wrappers.ts, src/pages/Overview/BalanceChart/defaults.ts, src/pages/Overview/BalanceChart/index.tsx, src/pages/Overview/BalanceChart/types.ts, src/pages/Overview/BalanceLinks.tsx, src/pages/Overview/Wrappers.ts, src/pages/Overview/index.tsx, src/pages/Payouts/index.tsx, src/pages/Pools/index.tsx, src/pages/Validators/index.tsx
Some work on abstracting `BalanceChart` into more components, simplifying the CSS, and preparing it for re-use with more data.
=> BalanceChart abstraction

src/contexts/Api/index.tsx, src/modals/UnlockChunks/Forms.tsx, src/modals/WithdrawPoolMember/index.tsx
Fixes an issue where historyDepth was in BigNumber format instead of a string.
=> History Depth Tx Fix

src/contexts/FastUnstake/index.tsx, src/library/Graphs/Utils.ts
This PR links to the issue #665
=> Introduce Array.at(index)

src/contexts/Account/index.tsx, src/contexts/Pools/BondedPools/index.tsx, src/contexts/Pools/PoolMembers/index.tsx, src/contexts/Validators/index.tsx
Fixes an issue where meta batch state was not being updated correctly.
=> Meta Batch state fix

src/library/Hooks/useTimeLeft/index.tsx, src/modals/LeavePool/index.tsx, src/modals/Unbond/index.tsx, src/modals/UnbondPoolMember/index.tsx, src/modals/UnlockChunks/Chunk.tsx, src/modals/UnlockChunks/Overview.tsx, src/modals/Unstake/index.tsx, src/modals/Utils/StaticNote.tsx, src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
Fixes an issue where time-left displays would jump forward a matter of seconds due to re-renders resetting the start date.
=> Timeleft re-rendering fix

src/library/Hooks/useValidatorFilters/index.tsx, src/library/ValidatorList/index.tsx
Fixes an issue where deleting a multi-character search term from the search bar resulted in no results being displayed.
=> fix empty search results on empty search

src/modals/ConnectAccounts/Account.tsx, src/modals/ConnectAccounts/Accounts.tsx, src/modals/ConnectAccounts/Wrappers.ts, src/modals/ConnectAccounts/types.ts, src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
=> Remove controller accounts from account selection

src/contexts/Subscan/index.tsx
This PR improves the structure of the Subscan context, and sets the state for claimed & unclaimed payouts, and pool claims, all in one render. 
This PR also limits Subscan requests to 1 page for payouts, and 1 page for pool claims, to prevent unwanted throttling.
=> Unify payouts state update + fix Subscan throttle

src/library/ListItem/Labels/Identity.tsx, src/library/ListItem/types.ts, src/library/ValidatorList/Validator/Default.tsx, src/library/ValidatorList/Validator/Nomination.tsx, src/pages/Payouts/PayoutList/index.tsx, src/pages/Pools/Home/MembersList/Member.tsx
Fixes an issue where an identity was not updating and instead falling back to the address.
=> Identity re-render fix

src/Wrappers.tsx, src/library/Overlay/Wrappers.tsx, src/library/SideMenu/Primary/Wrappers.tsx, src/library/Stat/Wrapper.ts, src/pages/Overview/StakeStatus/Wrappers.tsx, src/pages/Overview/Wrappers.ts
Makes `text-color-primary` and `text-color-secondary` more consistent.
=> Improved primary and secondary text theming

src/pages/Overview/StakeStatus/Tips/Wrappers.tsx, src/pages/Overview/StakeStatus/Wrappers.tsx, src/pages/Overview/StakeStatus/index.tsx
Simplifies the staking status design.
=> Simplify stake status

src/config/validators/index.ts
Hi, just a review in our current live validators.
Thank you
=> add turboflakes validators stash addresses

src/contexts/Hardware/Ledger.tsx, src/modals/Connect/index.tsx
This PR contains fixes after testing a Ledger Nano S Plus with staking dashboard.
=> Ledger Nano S Plus Fixes

src/Wrappers.tsx, src/pages/Nominate/Active/Status/index.tsx, src/pages/Overview/BalanceLinks.tsx, src/pages/Pools/Home/Status/index.tsx
Replacing the Separator from ./Wrapper with the UI one
=> Migrate Separator from UI

src/config/validators/index.ts, src/config/validators/thumbnails/VFValidierung.tsx
We renamed ourselves, therefore we updated the name in the dashboard.
=> renamed validator validierung.cc -> VF Validierung

src/contexts/Pools/ActivePools/defaults.ts, src/contexts/Pools/ActivePools/index.tsx, src/contexts/Pools/types.ts, src/modals/Bond/index.tsx, src/modals/ClaimReward/index.tsx, src/modals/LeavePool/index.tsx, src/modals/Unbond/index.tsx, src/pages/Pools/Home/Status/RewardsStatus.tsx
This PR replaces the `calculatePayout` function with the nomination pools `pendingRewards` runtime API.
=> Use nominationPoolsApi.pendingRewards

src/contexts/Staking/defaults.ts, src/contexts/Staking/index.tsx, src/contexts/Validators/defaults.ts, src/contexts/Validators/index.tsx, src/library/GenerateNominations/index.tsx
This PR simplifies some context syntax.
=> Staking & Validators Context Syntax Tidy-up

src/library/Import/Address.tsx, src/library/Import/Wrappers.ts, src/library/Import/types.ts, src/modals/ImportLedger/Addresses.tsx, src/modals/ImportVault/index.tsx
Iterates the `Address` component of hardware account importing.
=> Iterate hardware Address

src/contexts/Connect/defaults.ts, src/contexts/Connect/index.tsx, src/contexts/Connect/types.ts, src/contexts/Migrate/index.tsx, src/contexts/Proxies/index.tsx, src/modals/Accounts/Account.tsx, src/modals/Accounts/Delegates.tsx, src/modals/Accounts/types.ts
=> expand ActiveProxy & Migrate

README.md, src/Router.tsx, src/contexts/Connect/defaults.ts, src/contexts/Connect/index.tsx, src/contexts/Connect/types.ts, src/contexts/Extensions/index.tsx, src/locale/cn/library.json, src/locale/en/library.json
=> Connect to account on page load with `a` URL variable

src/library/GenerateNominations/index.tsx
Correct the max nominations selection from 17 to 16.
=> Fix max nominations bug

src/library/SelectItems/index.tsx, src/modals/Accounts/Delegates.tsx, src/modals/Accounts/index.tsx
Fix the key warnings from the Account modal
=> Fix keys warnings

src/contexts/Pools/PoolMemberships/index.tsx
=> Remove network limitation for claimPermission

package.json, src/library/SideMenu/Heading/Heading.tsx, src/library/SideMenu/Heading/Wrapper.tsx, src/library/SideMenu/Secondary/Wrappers.tsx, src/library/SideMenu/Secondary/index.tsx, src/library/SideMenu/types.ts, src/library/StatusLabel/Wrapper.ts, src/library/StatusLabel/index.tsx, src/library/StatusLabel/types.ts, src/library/SubscanButton/index.tsx, src/pages/Overview/StakeStatus/Tips/Syncing.tsx, src/pages/Overview/StakeStatus/Tips/Wrappers.tsx, yarn.lock
=> Update to styled components 6

package.json, src/Router.tsx, src/library/Background/index.tsx, src/library/Help/index.tsx, src/modals/index.tsx, yarn.lock
Unifying the background of modal and help. 
This will allow modals and canvas based overlays to open and close without the background fading out.
=> Modal & Help background as separate component

src/modals/Accounts/Account.tsx, src/modals/Accounts/Wrappers.ts
Amends the styling of accounts modal.
=> Accounts modal styling

src/library/BarChart/LegendItem.tsx, src/library/BarChart/Wrappers.ts, src/library/BarChart/types.ts, src/library/List/MotionContainer.tsx, src/library/Modal/Title.tsx, src/modals/UpdateReserve/index.tsx, src/pages/Overview/BalanceChart.tsx, src/pages/Overview/BalanceLinks.tsx
Moves the reserve button to `BalanceChart`.
=> Update reserve button refactor

.eslintrc.json, src/contexts/Connect/Utils.ts, src/contexts/Identities/index.tsx, src/contexts/Notifications/index.tsx, src/contexts/Pools/BondedPools/index.tsx, src/contexts/Pools/PoolMembers/index.tsx, src/contexts/Validators/index.tsx, src/library/Form/Unbond/UnbondFeedback.tsx, src/library/GenerateNominations/index.tsx, src/library/GenerateNominations/useFetchMethods.tsx, src/library/Help/index.tsx, src/library/Hooks/usePrices/index.tsx, src/library/ListItem/Labels/PoolBonded.tsx, src/library/QRCode/Scan.tsx, src/library/QRCode/ScanSignature.tsx, src/library/SideMenu/Main.tsx, src/modals/NominateFromFavorites/index.tsx, src/modals/SelectFavorites/index.tsx, src/modals/UnlockChunks/Overview.tsx, src/modals/ValidatorMetrics/index.tsx, src/pages/Nominate/Active/Nominations/index.tsx, src/pages/Overview/StakeStatus/Tips/index.tsx, src/pages/Pools/Home/Favorites/index.tsx
This PR fixes the codebase of the `no-underscore-dangle` rule and enables it in `eslintrc.json`.
=> Active no-underscore-dangle eslint

src/contexts/Connect/Hooks/useImportExtension.tsx, src/contexts/Connect/Utils.ts, src/contexts/Connect/index.tsx, src/contexts/Extensions/index.tsx
This PR abstracts some Connect context functions, improves comments and code structure.
This will improve app efficiency, but also prep this context for the upcoming Connect component where a lot of this code will be abstracted into a package.
=> Improve Connect context, minimise duplicate code

src/pages/Pools/Home/Favorites/index.tsx
Fixes an issue where favorite pools would crash upon visiting the tab.
=> fix: fix bug on favorite pools visit

src/config/help.ts, src/locale/en/help.json
Removes stale controller help content as we further deprecate the feature.
=> feat(help): remove controller help items

src/config/networks.ts, src/contexts/Api/defaults.ts, src/contexts/Api/index.tsx, src/contexts/Api/types.ts, src/contexts/UI/defaults.ts, src/contexts/UI/index.tsx, src/contexts/UI/types.ts, src/library/Prompt/Wrappers.ts, src/modals/Networks/ProvidersPrompt.tsx, src/modals/Networks/Wrapper.ts, src/modals/Networks/index.tsx, src/types/index.ts
=> feat: allow selection of RPC providers

src/modals/Networks/index.tsx
Fix the"Provider:" text to follow the theme
=> Fix minor text theme bug

src/contexts/Hardware/Ledger/LedgerHardware.tsx, src/contexts/Hardware/Ledger/types.ts, src/contexts/Hardware/Utils.tsx, src/locale/cn/modals.json, src/locale/en/modals.json
Adds method not supported error to Ledger error handling.
=> feat: add MethodNotSupported error to ledger

src/library/Form/Bond/BondFeedback.tsx, src/library/Form/Bond/BondInput.tsx, src/library/Form/Unbond/UnbondFeedback.tsx, src/library/Form/Unbond/UnbondInput.tsx, src/library/Form/types.ts, src/library/SetupSteps/Nominate.tsx, src/modals/Bond/index.tsx, src/modals/JoinPool/index.tsx, src/modals/Unbond/index.tsx, src/pages/Nominate/Setup/Bond/index.tsx, src/pages/Pools/Create/Bond/index.tsx, src/pages/Pools/Home/Status/useStatusButtons.tsx
Miscellaneous fixes to bonding.
=> fix: Bond fixes

package.json, src/contexts/Connect/OtherAccounts/index.tsx, yarn.lock
Fixes pertaining to importing local accounts.
=> fix: local account import fixes

package.json, src/contexts/Api/index.tsx, src/static/APController/index.ts, yarn.lock
This PR adds connection re-attempts to `APIController` to work with both Polkadot JS API and light client.
=> feat: offline recovery

src/static/APController/index.ts
This PR adds a block verification interval, checking if blocks are coming in. This is a decentralised polling mechanism to check whether the dapp still "online", .or has access to the API. This is needed as Polkadot JS API can report false positive `connected` events when VPNs or virtualisation is running. Even though it would think it is connected, blocks would not be coming in.
A `disconnect` is triggered if blocks are not syncing, and the reconnect loop is initiated to attempt reconnection.
=> feat: add block verification interval

src/canvas/ManageNominations/index.tsx, src/contexts/Help/index.tsx, src/contexts/UI/index.tsx, src/locale/utils.ts, src/modals/ManagePool/Forms/ManageCommission/ChangeRate.tsx
Corrected few typo fix I came across. Hope I could help.
=> chore: few typo fix

src/contexts/Api/defaults.ts, src/contexts/Api/index.tsx, src/contexts/Api/types.ts, src/contexts/Pools/BondedPools/index.tsx, src/contexts/Pools/PoolsConfig/defaults.ts, src/contexts/Pools/PoolsConfig/index.tsx, src/contexts/Pools/PoolsConfig/types.ts, src/library/Form/Bond/BondFeedback.tsx, src/library/Form/CreatePoolStatusBar/index.tsx, src/library/Form/Unbond/UnbondFeedback.tsx, src/library/Hooks/useFillVariables/index.tsx, src/library/Hooks/usePoolCommission/index.tsx, src/modals/ManagePool/Forms/ManageCommission/index.tsx, src/modals/ManagePool/Tasks.tsx, src/modals/Unbond/index.tsx, src/pages/Overview/NetworkSats/Announcements.tsx, src/pages/Pools/Create/Summary/index.tsx, src/pages/Pools/Home/Stats/ActivePools.tsx, src/pages/Pools/Home/Stats/MinCreateBond.tsx, src/pages/Pools/Home/Stats/MinJoinBond.tsx, src/pages/Pools/Home/Status/useStatusButtons.tsx, src/pages/Pools/Home/index.tsx, src/static/APIController/index.ts, src/types/index.ts
Adds pool config to initial app state bootstrapping, and subscription is now managed through APIController.
=> feat(refacor): Pool config to bootstrap app state

src/contexts/Pools/ActivePools/index.tsx, src/static/APIController/index.ts
=> fix: stricter member count fetching

src/library/Pool/index.tsx, src/locale/cn/library.json, src/locale/cn/modals.json, src/locale/en/library.json, src/locale/en/modals.json, src/modals/ManagePool/Tasks.tsx, src/modals/ManagePool/Wrappers.ts, src/modals/ManagePool/index.tsx
- Adds the ability to copy a pool's reward address from the All Pools list.
- Adds UI displaying a pool's stash and reward addresses in the Manage Pool modal.
=> feat(ux): View & copy pool addresses

src/library/GenerateNominations/index.tsx, src/library/ValidatorList/index.tsx
Fixes an issue where the manage nominations UI would not refresh when nominations were updated.
=> fix: fix manage nominations refresh

src/library/GenerateNominations/index.tsx
Fixes an object comparison by stringifying the values.
=> fix: stringify nomination comparison

src/contexts/Connect/OtherAccounts/index.tsx, src/contexts/FastUnstake/index.tsx, src/contexts/Proxies/index.tsx
Fixes edge cases around fast unstake and proxy state upon account and network changes.
=> fix: fast unstake, proxy fixes on account & network switch

src/pages/Overview/BalanceChart.tsx
Removes a conditional that removed reserve UI if reserve balance is zero.
=> fix: always show reserve

.licenserc.json, src/Themes.tsx, src/theme/accents/kusama-relay.css, src/theme/accents/polkadot-relay.css, src/theme/accents/westend-relay.css
=> fix: add CSS license check

src/contexts/Api/index.tsx, src/static/APIController/index.ts, src/static/ActivePoolsController/index.ts, src/static/BalancesController/index.ts
Prior to this PR offline events completely wiped out controller state. This PR amends the logic to keep controller state intact, in an attempt to recover from offline events more gracefully. 
There is still some re-syncing happening on the React side, but with that said, UX has been improved. Future PRs can further improve syncing logic on the UI side.
=> feat(refactor): Softer offline events

src/canvas/JoinPool/Wrappers.ts, src/library/Card/Wrappers.ts, src/library/Form/Warning/Wrapper.ts, src/library/Form/Warning/index.tsx, src/library/Pool/Rewards.tsx, src/library/SideMenu/Primary/Wrappers.ts, src/theme/theme.scss
Theming amendments
- Amends warning styles to use the secondary accent color.
- Pool performance to use primary accent color.
=> feat(ux): use secondary accent color for status UI

src/canvas/JoinPool/Preloader.tsx, src/canvas/JoinPool/Wrappers.ts, src/canvas/Wrappers.ts, src/library/PoolSync/Bar.tsx
replaces percentage with progress bar when fetching pool performance data.
=> feat: Join pool progress bar on performance fetch.

src/locale/cn/modals.json, src/locale/en/modals.json, src/modals/Connect/Extension.tsx, src/modals/Connect/Wrappers.ts
This PR adds the ability to disconnect from an extension. Upon a disconnect confirmation, local storage is updated and the dashboard reloads.
=> feat(ux): Disconnect from extension

src/contexts/Pools/ActivePool/index.tsx
Fixes an issue where active pools were being unsubscribed to on active account change.
=> fix(pools): don't unsubscribe from ActivePools 

src/pages/Overview/StakeStatus/Wrappers.ts, src/pages/Overview/StakeStatus/index.tsx
Fixes a prop name to be transient.
=> fix: use transient prop for styled components

package.json, src/contexts/Connect/Utils.ts, src/library/AccountInput/index.tsx, src/library/PayeeInput/index.tsx, src/modals/ImportVault/Reader.tsx, src/pages/Pools/Roles/RoleEditInput/index.tsx, yarn.lock
Uses formatAccountSs58 from `@w3ux/utils`.
=> feat(refactor): Use formatAccountSs58 util

src/contexts/Filters/index.tsx, src/library/PoolList/index.tsx, src/library/ValidatorList/index.tsx
Fixes an issue where filters were not being applied to search terms. Also applied the logic to orders.
=> fix: Search filters fix

src/config/networks.ts, src/consts.ts, src/controllers/IdentitiesController/index.ts
Fixes paged rewards and identities refactor with Polkadot spec 1,002,000.
=> feat: Runtime upgrade 1,002,000 fixes

src/contexts/Payouts/index.tsx
Fixes miscellaneous issues with paged rewards unclaimed payout logic.
- Fixes accessing an exposed page from local era exposures.
- Defaults a page to 0 instead of 1 when not found.
- Fixes an issue where the local storage record of an unclaimed payout was not removed on a successful claim.
=> fix: Paged rewards unclaimed payout fixes

package.json, src/consts.ts, src/contexts/Migrate/index.tsx, src/locale/index.tsx
Removes duplicate app version record. Bumps version.
=> feat(refactor): Use package.json version

package.json, yarn.lock
Prevents polkagate snap popup unless explicitly connected.
=> fix: prevent polkagate snap popup unless explicitly connected

src/contexts/LedgerHardware/index.tsx
Restores state updates for ledger tx signing, that were removed when the generic ledger app support was introduced.
=> fix: ledger hardware patch

package.json, yarn.lock
=> chore: bump `@w3ux/utils`

package.json, src/App.tsx, src/consts.ts, src/contexts/Api/defaults.ts, src/contexts/Api/types.ts, src/contexts/Pools/BondedPools/index.tsx, src/hooks/useBuildPayload/index.tsx, src/hooks/useCreatePoolAccounts/index.tsx, src/hooks/useValidatorFilters/index.tsx, src/library/Account/PoolAccount.tsx, src/library/QRCode/Display.tsx, src/library/QRCode/DisplayPayload.tsx, src/library/QRCode/Wrappers.ts, src/library/QRCode/constants.ts, src/library/QRCode/types.ts, src/library/QRCode/util.ts, src/library/ValidatorList/ValidatorItem/Utils.tsx, src/modals/ManagePool/Forms/RenamePool/index.tsx, yarn.lock
Drawing down usage of `@polkadot/util`, and simplifying QR support.
=> feat(refactor): draw down @polkadot utils

packages/app/src/library/GenerateNominations/index.tsx, packages/app/src/library/List/Selectable.tsx, packages/app/src/library/List/index.ts
Fixes a theming issue where Selectable buttons were not being styled in dark mode.
=> fix: theme Selectable buttons

packages/app/src/api/index.ts
Filters non-encrypted boot node websockets
=> feat(light client): Use wss boot nodes only

packages/app/src/api/subscribe/activePoolAccount/index.ts, packages/app/src/common-types.ts, packages/app/src/contexts/Pools/ActivePool/defaults.ts, packages/app/src/contexts/Pools/ActivePool/index.tsx, packages/app/src/contexts/Pools/ActivePool/types.ts, packages/app/src/controllers/ActivePools/index.ts, packages/app/src/hooks/useActivePools/index.tsx, packages/types/src/pools.ts
Fixes an issue where a removed pool was not being deleted from UI state.
=> feat(fix): Remove left pool from state

.release-please-manifest.json
Updates release please manifest file.
=> chore: update release please manifest

.release-please-manifest.json
Updates release please manifest versions.
=> chore: update release please

.github/dependabot.yml
Groups dependabot updates to minimise PRs.
=> chore: Group Dependabot updates & optimisations

packages/app/src/hooks/useProxySupported/index.tsx
fixes a condition for `Utility.batch`.
=> fix: batch call test

packages/app/src/overlay/canvas/Pool/Header.tsx, packages/app/src/overlay/canvas/ValidatorMetrics/index.tsx, packages/ui-core/src/canvas/HeadTags/index.module.scss
Adds commission label to Pool canvas, misc styling.
=> feat: Add pool commission label to `Pool` canvas

packages/app/src/library/List/Utils.tsx, packages/app/src/library/List/types.ts, packages/app/src/library/ListItem/Labels/Identity.tsx, packages/app/src/library/NominationList/Item.tsx, packages/app/src/library/ValidatorList/Item.tsx, packages/app/src/overlay/canvas/Pool/Overview/Roles.tsx, packages/app/src/overlay/canvas/Pool/index.tsx, packages/app/src/overlay/canvas/Pool/types.ts, packages/app/src/pages/Pools/PoolAccount/index.tsx, packages/ui-core/src/base/Identity/index.tsx, packages/ui-core/src/base/types.ts, packages/ui-identity/src/index.tsx, packages/ui-identity/src/types.ts
Injects pool role identities data into the `Pool` canvas, and improves the handling of Identities across UI components.
=> feat(ux): Plug role identities into `Pools` canvas, improve identity handling

packages/app/src/library/Card/Wrappers.ts, packages/app/src/pages/Overview/StakeStatus/Tips/PageToggle.tsx, packages/app/src/pages/Overview/StakeStatus/Tips/Wrappers.ts, packages/app/src/pages/Overview/StakeStatus/Tips/index.tsx, packages/app/src/pages/Overview/StakeStatus/Wrappers.ts
Some styling amendments to minify and simplify the stake status and tips UI on the Overview page.
=> feat(ux): Minify tips toggle

packages/app/src/library/Card/Wrappers.ts, packages/app/src/library/MainFooter/index.tsx, packages/consts/src/index.ts, packages/styles/theme/_variables.scss, packages/styles/theme/index.scss, packages/ui-core/src/base/Page/Container/index.module.scss, packages/ui-core/src/base/Page/Container/index.tsx, packages/ui-core/src/base/Page/RowSection/index.module.scss, packages/ui-core/src/base/Page/RowSection/index.tsx
Adjusts the behaviour of `RowSection`s to expand to a full-width component within a higher width, preventing the huddling of app content.
=> feat(ux) Structural improvements to `RowSection` and app padding

packages/app/package.json, packages/app/src/library/Balance/Value/index.tsx, packages/app/src/library/Balance/WithFiat/index.tsx, packages/app/src/library/Balance/index.tsx, packages/app/src/library/BarChart/Wrappers.ts, packages/app/src/overlay/modals/RewardCalculator/index.tsx, packages/app/src/pages/Overview/AccountBalance/BalanceChart.tsx, packages/app/src/pages/Overview/Payouts/index.tsx, packages/app/src/pages/Overview/Wrappers.ts, packages/app/src/pages/Overview/index.tsx, packages/app/src/pages/Rewards/Overview/index.tsx, packages/ui-core/src/base/TokenFiat/index.module.scss, yarn.lock
Enhances Balance component for Overview page to display fiat value on a second row.
Addresses fiat value placement for https://github.com/polkadot-cloud/polkadot-staking-dashboard/pull/2563
=> feat(ux): Expanded balance UI on `Overview`

packages/app/src/library/Nominations/index.tsx, packages/app/src/overlay/canvas/ManageNominations/index.tsx, packages/app/src/pages/Nominate/Active/CommissionPrompt.tsx, packages/app/src/pages/Nominate/Active/index.tsx, packages/app/src/pages/Pools/ManagePool/index.tsx, packages/types/src/index.ts, packages/types/src/overlay.ts, packages/ui-core/src/canvas/Footer/index.module.scss, packages/ui-core/src/canvas/Footer/index.tsx, packages/ui-core/src/canvas/Main/index.module.scss, packages/ui-core/src/canvas/Main/index.tsx, packages/ui-core/src/canvas/Scroll/index.module.scss, packages/ui-core/src/canvas/_variables.scss, packages/ui-overlay/package.json, packages/ui-overlay/src/Background.tsx, packages/ui-overlay/src/Provider/index.tsx, packages/ui-overlay/src/Provider/types.ts, yarn.lock
Adds support for canvas interfaces to be full screen width. Re-organises some types around the overlay to be used throughout the monorepo.
=> feat(ux): Add canvas max width support

.prettierignore, packages/app/package.json, pnpm-lock.yaml
Updates to the latest `@w3ux/react-connect-kit` that refactors extension discovery to the new `@w3ux/observables-connect` package.
=> feat(refactor): use latest connect kit w. observables

package.json, packages/app/package.json, packages/app/src/Providers.tsx, packages/app/src/contexts/Connect/ExternalAccounts/Utils.ts, packages/app/src/contexts/Connect/ExternalAccounts/index.tsx, packages/app/src/contexts/Connect/OtherAccounts/index.tsx, packages/app/src/contexts/Connect/OtherAccounts/types.ts, packages/app/src/contexts/LedgerHardware/Utils.tsx, packages/app/src/hooks/useSubmitExtrinsic/index.tsx, packages/app/src/library/QrReader/index.tsx, packages/app/src/overlay/modals/ImportAccounts/Ledger.tsx, packages/app/src/overlay/modals/ImportAccounts/Vault.tsx, packages/app/src/overlay/modals/ImportAccounts/WalletConnect.tsx, packages/ui-buttons/package.json, packages/ui-core/src/base/AccountImport/Item/index.tsx, packages/ui-core/src/base/AccountImport/types.ts, pnpm-lock.yaml
This pull request introduces a significant refactor aimed at unifying the hardware account providers within the Polkadot Staking Dashboard. The key changes include:
- Unified Hardware Account Providers: Consolidated the implementations of various hardware account providers into a single, cohesive module to enhance maintainability and consistency across the codebase.
- Codebase Simplification: Achieved a net reduction of 53 lines of code (added 151 lines, removed 204 lines), resulting in a more streamlined and efficient code structure.
=> feat(refactor): Unified hardware account providers

packages/app/package.json, packages/app/src/contexts/LedgerHardware/static/ledger.ts, packages/app/src/library/Signers/LedgerSigner.ts, pnpm-lock.yaml
Fixes breaking changes for latest `@zondax/ledger-substrate` version.
=> feat(fix): Fix `@zondax/ledger-substrate` breaking changes

packages/ui-core/src/modal/Scroll/index.module.scss, packages/ui-core/src/modal/Scroll/index.tsx, packages/ui-core/src/modal/types.ts, packages/ui-overlay/src/Modal.tsx, pnpm-lock.yaml
Simplebar is now acting as the modal scrollbar.
=> feat(ux): Simplebar to modal

packages/app/src/overlay/canvas/ManageNominations/index.tsx, packages/styles/theme/index.scss, packages/ui-overlay/src/CloseCanvas.tsx, packages/ui-overlay/src/Provider/index.tsx
Stops the body from scrolling while the canvas is open.
=> feat(ux): Stop body scroll on canvas open

packages/app/src/contexts/UI/index.tsx, packages/app/src/library/SideMenu/index.tsx
Always shows side menu labels in simple mode for a more intuitive UI.
=> feat(ux): Force show labels in simple mode

packages/app/src/library/QRCode/Scan.tsx, packages/app/src/library/Signers/VaultSigner/index.ts, packages/app/src/pages/Overview/AccountBalance/BalanceChart.tsx
- Replace console.error with proper error callback in QR scanner
- Throw Error objects instead of strings in VaultSigner
- Ensures consistent error handling and better debugging capabilities
=> fix: improve error handling consistency across QR and Vault signers

.release-please-manifest.json, packages/app/CHANGELOG.md, packages/app/package.json, packages/assets/CHANGELOG.md, packages/assets/package.json, packages/consts/CHANGELOG.md, packages/consts/package.json, packages/locales/CHANGELOG.md, packages/locales/package.json, packages/plugin-staking-api/CHANGELOG.md, packages/plugin-staking-api/package.json, packages/styles/CHANGELOG.md, packages/styles/package.json, packages/types/CHANGELOG.md, packages/types/package.json, packages/ui-buttons/CHANGELOG.md, packages/ui-buttons/package.json, packages/ui-core/CHANGELOG.md, packages/ui-core/package.json, packages/ui-graphs/CHANGELOG.md, packages/ui-graphs/package.json, packages/ui-overlay/CHANGELOG.md, packages/ui-overlay/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
Reverts polkadot-cloud/polkadot-staking-dashboard#2560
=> Revert "chore: release main"

packages/app/src/library/SideMenu/Primary/Wrappers.ts, packages/app/src/library/SideMenu/Primary/index.tsx
This PR removes a double button structure in the side menu component by extracting navigation logic and refactoring the component structure to have proper button elements for both minimized and non-minimized states.
=> fix: Remove double button
